function cfg = candidate_template()
%CANDIDATE_TEMPLATE Copy and replace every placeholder before building.

cfg = struct();
cfg.schema_version = 1;
cfg.kind = 'cell';
cfg.id = 'candidate_template';
cfg.is_template = true;
cfg.manufacturer = 'REPLACE_ME';
cfg.model = 'REPLACE_ME';
cfg.nominal_capacity_Ah = NaN;
cfg.nominal_voltage_V = NaN;
cfg.minimum_voltage_V = NaN;
cfg.maximum_voltage_V = NaN;
cfg.maximum_charge_current_A = NaN;
cfg.maximum_discharge_current_A = NaN;

cfg.soc_breakpoints = linspace(0.10, 1.00, 12).';
cfg.ocv_soc_breakpoints = (0.00:0.01:1.00).';
cfg.temperature_breakpoints_C = [0, 25, 45].';
cfg.temperature_model_limits_C = [0, 45];
cfg.current_sign = 'positive_discharge';
cfg.dataset_adapter = 'load_generic_csv';

cfg.parameter_fit_options = struct( ...
    'cell_ids', {{'REPLACE_ME'}}, ...
    'ocv_cell_id', 'REPLACE_ME', ...
    'hcgt_soc_regions', [0.95, 0.85, 0.75, 0.65, 0.50, 0.35, 0.25, 0.15, 0.05], ...
    'r0_soc_regions', [0.95, 0.85, 0.75, 0.65, 0.50, 0.35, 0.25, 0.15, 0.05], ...
    'current_tolerance_fraction', 0.25, ...
    'rest_current_threshold_A', 0.20, ...
    'minimum_valid_fast_fits', 3, ...
    'minimum_valid_slow_fits', 10, ...
    'ocv_voltage_bounds_V', [0, Inf], ...
    'r0_bounds_ohm', [1e-5, 1], ...
    'r1_bounds_ohm', [1e-5, 1], ...
    'c1_bounds_F', [1, 1e7], ...
    'tau1_bounds_s', [0.1, 1000], ...
    'r2_bounds_ohm', [1e-5, 1], ...
    'c2_bounds_F', [1, 1e8], ...
    'tau2_bounds_s', [1, 5000], ...
    'fallback_R1_ohm', NaN, ...
    'fallback_C1_F', NaN, ...
    'fallback_R2_ohm', NaN, ...
    'fallback_C2_F', NaN);

cfg.thermal_prior = struct( ...
    'Cc_J_per_K', NaN, ...
    'Cs_J_per_K', NaN, ...
    'Rcs_K_per_W', NaN, ...
    'Rsa_K_per_W', NaN, ...
    'status', 'REPLACE_ME with measured data or justified prior');

cfg.parameter_source = struct( ...
    'mode', 'refit', ...
    'legacy_snapshot_file', '');
cfg.provenance = struct( ...
    'dataset', 'REPLACE_ME', ...
    'dataset_owner', 'REPLACE_ME', ...
    'parameter_status', 'template only', ...
    'known_limitations', {{'Not buildable until all placeholders are replaced.'}});
end
