function cfg = us06_25c()
%US06_25C Embedded US06 pack-current trace at 25 degC.

paths = hil.project_paths();
cfg = struct();
cfg.schema_version = 1;
cfg.kind = 'simulation';
cfg.id = 'us06_25c';
cfg.sample_time_s = 0.1;
cfg.stop_time_s = 'profile';
cfg.profile = struct( ...
    'name', 'us06_25c', ...
    'kind', 'embedded_c_header', ...
    'source_file', fullfile(paths.esp32_plant, 'main', 'drive_profiles.h'), ...
    'array_name', 'us06_25_i_10ma', ...
    'current_scale_A_per_count', 0.01, ...
    'source_sample_time_s', 0.1, ...
    'scaling_mode', 'vehicle_current_replay', ...
    'repeat_policy', 'one_shot');
cfg.ambient_temperature_C = 25.0;
cfg.initial_soc = 1.0;
cfg.measurement_noise = struct( ...
    'voltage_std_V', 0.0, ...
    'current_std_A', 0.0, ...
    'temperature_std_C', 0.0, ...
    'seed', 1002);
cfg.current_bias_A = 0.0;
cfg.fault_injection = struct('enabled', false);
cfg.output_directory = fullfile(paths.output_root, cfg.id);
cfg.engine = 'auto';
end
