function cfg = structural_12s2p()
%STRUCTURAL_12S2P Deliberately different topology used as a regression test.

Ns = 12;
Np = 2;
segment_counts = [4, 4, 4];
Nsegments = numel(segment_counts);
Ntemp = 18;

cfg = struct();
cfg.schema_version = 1;
cfg.kind = 'pack';
cfg.id = 'structural_12s2p';
cfg.is_template = false;
cfg.series_groups = Ns;
cfg.parallel_cells = Np;
cfg.segment_count = Nsegments;
cfg.groups_per_segment = segment_counts;
cfg.group_to_segment = repelem(1:Nsegments, segment_counts);
cfg.temperature_sensor_count = Ntemp;
cfg.temp_sensor_to_group = repelem(1:Ns, [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1]);
cfg.temp_sensor_location_type = repmat({'cell_surface'}, 1, Ntemp);
cfg.temp_sensor_location_type(3:3:end) = {'interstitial'};
cfg.temp_sensor_core_weight = zeros(1, Ntemp);
cfg.temp_sensor_core_weight(3:3:end) = 0.50;
cfg.initial_soc = 0.85;
cfg.initial_temperature_C = 25.0;
cfg.minimum_group_voltage_V = 2.5;
cfg.maximum_group_voltage_V = 4.2;

cfg.imbalance_model = struct( ...
    'mode', 'parameter_distributed', ...
    'seed', 12002, ...
    'voltage_peak_to_peak_V', 0.008, ...
    'soc_peak_to_peak', 0.010, ...
    'temperature_peak_to_peak_C', 2.0, ...
    'capacity_sigma_fraction', 0.015, ...
    'capacity_bounds_fraction', [0.95, 1.05], ...
    'r0_sigma_fraction', 0.035, ...
    'r0_bounds_fraction', [0.90, 1.12], ...
    'r1_sigma_fraction', 0.035, ...
    'r1_bounds_fraction', [0.90, 1.12], ...
    'c1_sigma_fraction', 0.020, ...
    'c1_bounds_fraction', [0.94, 1.06], ...
    'r2_sigma_fraction', 0.035, ...
    'r2_bounds_fraction', [0.90, 1.12], ...
    'c2_sigma_fraction', 0.020, ...
    'c2_bounds_fraction', [0.94, 1.06], ...
    'initial_soc_sigma', 0.0025, ...
    'initial_soc_bounds', [-0.005, 0.005], ...
    'thermal_resistance_sigma_fraction', 0.08, ...
    'thermal_resistance_bounds_fraction', [0.80, 1.25]);

cfg.thermal_layout = struct( ...
    'model', 'explicit_sensor_to_group_mapping', ...
    'cell_to_cell_coupling_K_per_W', NaN, ...
    'module_conduction_K_per_W', NaN, ...
    'busbar_heat_model', 'not_calibrated', ...
    'geometry_status', 'structural test only');
cfg.cooling_boundary = struct( ...
    'mode', 'natural_convection_nominal', ...
    'Rsa_multiplier', 1.0, ...
    'ambient_temperature_C', 25.0, ...
    'assumption', 'structural test only');
end
