clear; clc;

mdl = 'drev_75s6p_p42a_accumulator_plant_v3_ams_outputs_validated';

param_file = fullfile(getenv('USERPROFILE'), ...
    'Documents', 'BMS_P42A_Data', 'mat_params', ...
    'params_p42a_75s6p_final_batch_validated.mat');

load(param_file);
load_system(mdl);

%% Critical plant settings
set_param([mdl '/I_pack_to_cell'], 'Gain', '1/6');
set_param([mdl '/V_cell_to_pack'], 'Gain', '75');
set_param([mdl '/dSoC_per_step'], 'Gain', '-1/(3600*Q_nom)');
set_param([mdl '/SoC_Integrator'], 'SampleTime', '0.1');
set_param([mdl '/ T_clamp'], 'LowerLimit', '5', 'UpperLimit', '40');

%% Solver settings
set_param(mdl, ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', '0.1', ...
    'StartTime', '0', ...
    'StopTime', '10');

%% Codegen target
if license('test', 'RTW_Embedded_Coder')
    target = 'ert.tlc';
else
    target = 'grt.tlc';
end

set_param(mdl, ...
    'SystemTargetFile', target, ...
    'GenCodeOnly', 'on', ...
    'GenerateReport', 'on', ...
    'LaunchReport', 'off');

%% Code style / embedded-friendly options
set_param(mdl, ...
    'DefaultParameterBehavior', 'Inlined', ...
    'MatFileLogging', 'off', ...
    'SaveOutput', 'off', ...
    'SignalLogging', 'off', ...
    'SupportNonFinite', 'off', ...
    'ProdLongLongMode', 'on');

%% Function naming
set_param(mdl, ...
    'CustomSymbolStrGlobalVar', '$R$N$M', ...
    'CustomSymbolStrType', '$N$M_T', ...
    'CustomSymbolStrField', '$N$M', .slbuild('drev_75s6p_p42a_accumulator_plant_v3_ams_outputs_validated');..
    'CustomSymbolStrFcn', '$R$N$M$F');

%% Update and save
set_param(mdl, 'SimulationCommand', 'update');
save_system(mdl);

fprintf('\nConfigured codegen for:\n%s\n', mdl);
fprintf('Target file: %s\n', target);