% Generate a staged ERT component; parity-gated promotion is a separate step.
script_directory = fileparts(mfilename('fullpath'));
setup_hil
cell_configuration = hil.config.cell('p42a');
pack_configuration = hil.config.pack('der26_75s6p');
simulation_configuration = hil.config.simulation('hppc_validation');
[plant_parameters, parameter_build_report] = hil.build_parameters( ...
    cell_configuration, 'Save', false);
codegen_artifact = hil.generate_code( ...
    cell_configuration, pack_configuration, simulation_configuration, ...
    plant_parameters, 'InstallIntoEsp32', false);
disp(codegen_artifact)
fprintf([ ...
    '\nThe fresh component is staged and the frozen snapshot is unchanged.\n' ...
    'Run hash-chain verification, parity, staged ESP-IDF build, then promote:\n\n' ...
    '  python3 "%s" --artifact "%s" --promote\n\n'], ...
    fullfile(fileparts(fileparts(script_directory)), 'tools', ...
        'run_toolchain_qualification.py'), ...
    codegen_artifact.artifact_file);
