% Run the full reusable-framework validation suite.
setup_hil
validation_report = hil.validate_all( ...
    'RunDataset', true, 'RequireDataset', true, 'RunSimulink', 'auto');
assert(strcmp( ...
    validation_report.gates.p42a_dataset_validation.status, 'PASS'), ...
    'P42A electrical holdout validation did not pass.')
disp(validation_report.report_files)
