function cfg = c7_measurement_faults()
%C7_MEASUREMENT_FAULTS Stale/dropout/frozen/timing canonical case.
cfg=mil.default_config();cfg.id='c7_measurement_faults';
cfg.description='C7: stale/dropout/frozen-value/timestamp/sequence fault campaign';
cfg.initial_soc=0.50;cfg.stop_time_s=180;cfg.sensor.timestamp_jitter_std_s=0.005;
cfg.sensor.faults=[ ...
    struct('type','cell_stale','start_s',20,'end_s',35,'target',17,'value',300), ...
    struct('type','temperature_stale','start_s',45,'end_s',60,'target',30,'value',500), ...
    struct('type','pack_current_dropout','start_s',75,'end_s',77,'target',0,'value',0), ...
    struct('type','cell_open_wire_like','start_s',95,'end_s',110,'target',52,'value',0), ...
    struct('type','sequence_repeat','start_s',130,'end_s',135,'target',0,'value',0)];
cfg.sop_oracle.enabled=false;cfg.gates.ekf=false;
cfg.requirements={'C7-MEAS-FAULTS','MEAS-STALE','MEAS-VALIDITY','FAIL-CLOSED','TIMING-JITTER'};
cfg.tier='pr';
end
