/*
 * ams_can_logger.h
 * Author: Mahad Faisal (2026)
 *
 * Passive in-car AMS dashboard/logger CAN contract.
 *
 * These frames are intended for a read-only ESP32 dashboard/logger node. The
 * ESP32 must not be required for BMS_OK, charger control, ADBMS communication,
 * or any other safety output.
 */

#ifndef INC_EXT_DRIVERS_AMS_CAN_LOGGER_H_
#define INC_EXT_DRIVERS_AMS_CAN_LOGGER_H_

#include <stdint.h>

#define AMS_LOGGER_PROTOCOL_VERSION       3u

#define AMS_LOGGER_CAN_ID_HEARTBEAT       0x690u
#define AMS_LOGGER_CAN_ID_FAULT_REASONS   0x691u
#define AMS_LOGGER_CAN_ID_PACK_ELECTRICAL 0x692u
#define AMS_LOGGER_CAN_ID_TEMP_FAN        0x693u
#define AMS_LOGGER_CAN_ID_VOLTAGE_HEALTH  0x694u
#define AMS_LOGGER_CAN_ID_TEMP_HEALTH     0x695u
#define AMS_LOGGER_CAN_ID_CHARGER         0x696u
#define AMS_LOGGER_CAN_ID_CURRENT_DETAIL  0x697u
#define AMS_LOGGER_CAN_ID_6830_LINK       0x698u
#define AMS_LOGGER_CAN_ID_6830_COUNTERS   0x699u
#define AMS_LOGGER_CAN_ID_2950_LINK       0x69Au
#define AMS_LOGGER_CAN_ID_TASK_HEALTH     0x69Bu
#define AMS_LOGGER_CAN_ID_CAN_DIAG        0x69Cu
#define AMS_LOGGER_CAN_ID_SAFETY_DIAG     0x69Du
#define AMS_LOGGER_CAN_ID_WATCHDOG_DIAG   0x69Eu
#define AMS_LOGGER_CAN_ID_ADBMS_DIAG      0x69Fu

#define AMS_LOGGER_CAN_ID_CELL_DETAIL     0x6A0u
#define AMS_LOGGER_CAN_ID_TEMP_DETAIL     0x6A1u
#define AMS_LOGGER_CAN_ID_VOLTAGE_MASKS   0x6A2u
#define AMS_LOGGER_CAN_ID_TEMP_MASKS_A    0x6A3u
#define AMS_LOGGER_CAN_ID_TEMP_MASKS_B    0x6A4u
#define AMS_LOGGER_CAN_ID_VOLTAGE_PEC     0x6A5u
#define AMS_LOGGER_CAN_ID_CURRENT_ADC     0x6A6u
#define AMS_LOGGER_CAN_ID_CHARGER_DETAIL  0x6A7u
#define AMS_LOGGER_CAN_ID_TEMP_DIAG       0x6A8u
#define AMS_LOGGER_CAN_ID_TEMP_DIAG_A     0x6A9u
#define AMS_LOGGER_CAN_ID_TEMP_DIAG_B     0x6AAu
#define AMS_LOGGER_CAN_ID_VOLTAGE_DIAG    0x6ABu
#define AMS_LOGGER_CAN_ID_RTOS_DIAG       0x6ACu
#define AMS_LOGGER_CAN_ID_SNAPSHOT_META   0x6ADu
#define AMS_LOGGER_CAN_ID_APM_SAMPLE      0x6AEu
#define AMS_LOGGER_CAN_ID_APM_HEALTH      0x6AFu
#define AMS_LOGGER_CAN_ID_APM_RAW         0x6B0u
#define AMS_LOGGER_CAN_ID_ESTIMATOR       0x6B2u
#define AMS_LOGGER_CAN_ID_TX_SCHED_DIAG    0x6B3u
#define AMS_LOGGER_CAN_ID_ESTIMATOR_VOLTAGE_COMPARE 0x6B4u
#define AMS_LOGGER_CAN_ID_EKF_STATE       0x6B5u
#define AMS_LOGGER_CAN_ID_EKF_MODEL       0x6B6u
#define AMS_LOGGER_CAN_ID_EKF_COVARIANCE  0x6B7u
#define AMS_LOGGER_CAN_ID_EKF_SOH         0x6B8u
#define AMS_LOGGER_CAN_ID_EKF_CONTEXT     0x6B9u
#define AMS_LOGGER_CAN_ID_SOP_DISCHARGE   0x6BAu
#define AMS_LOGGER_CAN_ID_SOP_CHARGE      0x6BBu
#define AMS_LOGGER_CAN_ID_SOP_BINDING     0x6BCu
#define AMS_LOGGER_CAN_ID_FUSE_STATE      0x6BDu
#define AMS_LOGGER_CAN_ID_FUSE_LIMIT      0x6BEu
#define AMS_LOGGER_CAN_ID_TUNING_META     0x6BFu
#define AMS_LOGGER_CAN_ID_SOP_META        0x6C0u
#define AMS_LOGGER_CAN_ID_LAST            AMS_LOGGER_CAN_ID_SOP_META

/* Test/tuning telemetry is observational and is intentionally absent from a
 * 250-kbit/s image. It is always scheduled as disposable DETAIL traffic. */
#ifndef AMS_ENABLE_TUNING_CAN
#define AMS_ENABLE_TUNING_CAN (DER26_CAN_BITRATE_KBPS == 500u)
#endif

#if (AMS_ENABLE_TUNING_CAN != 0) && (AMS_ENABLE_TUNING_CAN != 1)
#error "AMS_ENABLE_TUNING_CAN must be 0 or 1"
#endif
#if (DER26_CAN_BITRATE_KBPS == 250u) && AMS_ENABLE_TUNING_CAN
#error "AMS tuning CAN is prohibited at 250 kbit/s"
#endif

#define AMS_TUNING_CAN_FAST_PERIOD_MS 100u
#define AMS_TUNING_CAN_SOP_PERIOD_MS  200u

#define AMS_TUNING_SUPPRESS_PROTECTED_DEADLINE (1u << 0u)
#define AMS_TUNING_SUPPRESS_PROTECTED_LATENCY  (1u << 1u)
#define AMS_TUNING_SUPPRESS_PROTECTED_HAL      (1u << 2u)
#define AMS_TUNING_SUPPRESS_CAN_TASK_DEADLINE  (1u << 3u)
#define AMS_TUNING_SUPPRESS_BUS_HEALTH         (1u << 4u)
#define AMS_TUNING_SUPPRESS_BUILD_INTEGRITY    (1u << 5u)

#define AMS_LOGGER_SNAPSHOT_VERSION       2u
#define AMS_LOGGER_PHASE_BITS              3u
#define AMS_LOGGER_PHASE_MASK              0x07u
#define AMS_LOGGER_FRAGMENT_SEQ_MASK       0x1Fu

/* V4 detail fragments carry the low five snapshot-sequence bits in the upper
 * bits of byte 0 and the SMB/phase in the lower three bits. This allows the
 * ECU to associate out-of-order detail fragments with their snapshot without
 * sacrificing any voltage/temperature payload bytes. */
static inline uint8_t ams_logger_phase_tag(uint8_t sequence, uint8_t phase)
{
    return (uint8_t)(((sequence & AMS_LOGGER_FRAGMENT_SEQ_MASK) <<
                      AMS_LOGGER_PHASE_BITS) |
                     (phase & AMS_LOGGER_PHASE_MASK));
}
static inline uint8_t ams_logger_phase_from_tag(uint8_t tag)
{
    return (uint8_t)(tag & AMS_LOGGER_PHASE_MASK);
}
static inline uint8_t ams_logger_seq5_from_tag(uint8_t tag)
{
    return (uint8_t)((tag >> AMS_LOGGER_PHASE_BITS) &
                     AMS_LOGGER_FRAGMENT_SEQ_MASK);
}

#define AMS_LOGGER_TEMP_INVALID_DECI_C    ((uint16_t)0x8000u)

typedef enum
{
    AMS_LOGGER_HEARTBEAT_FLAG_BMS_OK = 0,
    AMS_LOGGER_HEARTBEAT_FLAG_AIR_STATE,
    AMS_LOGGER_HEARTBEAT_FLAG_IMD_OK,
    AMS_LOGGER_HEARTBEAT_FLAG_HARD_FAULT,
    AMS_LOGGER_HEARTBEAT_FLAG_SOFT_FAULT,
    AMS_LOGGER_HEARTBEAT_FLAG_CHARGER_FAULT,
    AMS_LOGGER_HEARTBEAT_FLAG_CANBUS_FAULT,
    AMS_LOGGER_HEARTBEAT_FLAG_BMS_OUTPUT_INHIBIT
} ams_logger_heartbeat_flag_t;

typedef enum
{
    AMS_LOGGER_VALID_FLAG_VOLTAGE_VALID = 0,
    AMS_LOGGER_VALID_FLAG_CURRENT_VALID,
    AMS_LOGGER_VALID_FLAG_TEMP_VALID,
    AMS_LOGGER_VALID_FLAG_VOLTAGE_READ_FAULT,
    AMS_LOGGER_VALID_FLAG_TEMP_READ_FAULT,
    AMS_LOGGER_VALID_FLAG_CURRENT_SENSOR_FAULT,
    AMS_LOGGER_VALID_FLAG_VOLTAGE_LATCHED,
    AMS_LOGGER_VALID_FLAG_TEMP_LATCHED
} ams_logger_valid_flag_t;

typedef enum
{
    AMS_LOGGER_CURRENT_FLAG_FAULT = 0,
    AMS_LOGGER_CURRENT_FLAG_SENSOR_FAULT,
    AMS_LOGGER_CURRENT_FLAG_WARNING,
    AMS_LOGGER_CURRENT_FLAG_PENDING,
    AMS_LOGGER_CURRENT_FLAG_CONFIRMED,
    AMS_LOGGER_CURRENT_FLAG_LATCHED,
    AMS_LOGGER_CURRENT_FLAG_FUSE_FAULT,
    AMS_LOGGER_CURRENT_FLAG_ESTIMATOR_FAULT
} ams_logger_current_flag_t;


typedef enum
{
    AMS_LOGGER_SAFETY_FLAG_PANIC_ACTIVE = 0,
    AMS_LOGGER_SAFETY_FLAG_BMS_OUTPUT_INHIBIT,
    AMS_LOGGER_SAFETY_FLAG_BALANCE_INHIBIT,
    AMS_LOGGER_SAFETY_FLAG_BMS_STATE,
    AMS_LOGGER_SAFETY_FLAG_HARD_FAULT,
    AMS_LOGGER_SAFETY_FLAG_TASK_HEARTBEAT_FAULT,
    AMS_LOGGER_SAFETY_FLAG_LOGGER_HEARTBEAT_FAULT
} ams_logger_safety_flag_t;

typedef enum
{
    AMS_LOGGER_WATCHDOG_FLAG_RUNTIME_ENABLED = 0,
    AMS_LOGGER_WATCHDOG_FLAG_HW_STARTED,
    AMS_LOGGER_WATCHDOG_FLAG_FEED_GATE_OK
} ams_logger_watchdog_flag_t;

typedef enum
{
    AMS_LOGGER_ADBMS_DIAG_FLAG_DIAG_FAULT = 0,
    AMS_LOGGER_ADBMS_DIAG_FLAG_CONFIG_FAULT,
    AMS_LOGGER_ADBMS_DIAG_FLAG_STATUS_FAULT,
    AMS_LOGGER_ADBMS_DIAG_FLAG_OPEN_WIRE_FAULT,
    AMS_LOGGER_ADBMS_DIAG_FLAG_SCAN_ACTIVE,
    AMS_LOGGER_ADBMS_DIAG_FLAG_HIL_REPLACE,
    AMS_LOGGER_ADBMS_DIAG_FLAG_BALANCE_WRITE_FAULT,
    AMS_LOGGER_ADBMS_DIAG_FLAG_VOLTAGE_DEGRADED
} ams_logger_adbms_diag_flag_t;


typedef enum
{
    AMS_LOGGER_TEMP_DIAG_FLAG_OPEN = 0,
    AMS_LOGGER_TEMP_DIAG_FLAG_SHORT,
    AMS_LOGGER_TEMP_DIAG_FLAG_JUMP,
    AMS_LOGGER_TEMP_DIAG_FLAG_RATE_RISE,
    AMS_LOGGER_TEMP_DIAG_FLAG_FILTER_VALID
} ams_logger_temp_diag_flag_t;

typedef enum
{
    AMS_LOGGER_FAN_DIAG_FLAG_FAN_ON = 0,
    AMS_LOGGER_FAN_DIAG_FLAG_DRIVER_FAULT,
    AMS_LOGGER_FAN_DIAG_FLAG_TEMP_INVALID,
    AMS_LOGGER_FAN_DIAG_FLAG_TEMP_FAULT,
    AMS_LOGGER_FAN_DIAG_FLAG_TEMP_FAN_MAX
} ams_logger_fan_diag_flag_t;

typedef enum
{
    AMS_LOGGER_VOLTAGE_DIAG_FLAG_JUMP = 0,
    AMS_LOGGER_VOLTAGE_DIAG_FLAG_STUCK
} ams_logger_voltage_diag_flag_t;

typedef enum
{
    AMS_LOGGER_RTOS_FLAG_FAULT = 0,
    AMS_LOGGER_RTOS_FLAG_STACK_WARN,
    AMS_LOGGER_RTOS_FLAG_HEAP_WARN,
    AMS_LOGGER_RTOS_FLAG_STACK_OVERFLOW,
    AMS_LOGGER_RTOS_FLAG_MALLOC_FAILED,
    AMS_LOGGER_RTOS_FLAG_ASSERT_FAILED,
    AMS_LOGGER_RTOS_FLAG_STACK_CRITICAL
} ams_logger_rtos_diag_flag_t;

typedef enum
{
    AMS_LOGGER_HIL_FLAG_MEAS_FRESH = 0,
    AMS_LOGGER_HIL_FLAG_TRUTH_FRESH,
    AMS_LOGGER_HIL_FLAG_SUMMARY_FRESH,
    /* The upper five bits of ADBMS_DIAG byte 7 remain useful in physical-SPI
     * builds and make degraded measurement authority unambiguous. */
    AMS_LOGGER_ADBMS_STATE_FLAG_TEMP_UNAVAILABLE,
    AMS_LOGGER_ADBMS_STATE_FLAG_SMB_READY,
    AMS_LOGGER_ADBMS_STATE_FLAG_LAST_VOLTAGE_SCAN_OK,
    AMS_LOGGER_ADBMS_STATE_FLAG_C_ONLY_MODE,
    AMS_LOGGER_ADBMS_STATE_FLAG_S_REDUNDANCY_FAULT
} ams_logger_hil_flag_t;


typedef enum
{
    AMS_LOGGER_CURRENT_ADC_FLAG_HIGH_FRESH = 0,
    AMS_LOGGER_CURRENT_ADC_FLAG_LOW_FRESH,
    AMS_LOGGER_CURRENT_ADC_FLAG_LAST_READ_OK,
    AMS_LOGGER_CURRENT_ADC_FLAG_CURRENT_VALID,
    AMS_LOGGER_CURRENT_ADC_FLAG_SENSOR_FAULT,
    AMS_LOGGER_CURRENT_ADC_FLAG_ZERO_CALIBRATED
} ams_logger_current_adc_flag_t;

typedef enum
{
    AMS_LOGGER_CHARGER_FLAG_HW_FAIL = 0,
    AMS_LOGGER_CHARGER_FLAG_OVERTEMP_FAIL,
    AMS_LOGGER_CHARGER_FLAG_INPUT_VOLT_FAIL,
    AMS_LOGGER_CHARGER_FLAG_VOLTAGE_SENSE_FAIL,
    AMS_LOGGER_CHARGER_FLAG_COMM_FAIL,
    AMS_LOGGER_CHARGER_FLAG_TEMP_CHARGE_STOP,
    AMS_LOGGER_CHARGER_FLAG_VOLTAGE_CHARGE_STOP,
    AMS_LOGGER_CHARGER_FLAG_DISABLE_CHARGE
} ams_logger_charger_flag_t;

#endif /* INC_EXT_DRIVERS_AMS_CAN_LOGGER_H_ */
