/*
 * ams_can_logger.h
 * Author: Mahad Faisal (2026)
 *
 * Passive in-car AMS dashboard/logger CAN contract.
 *
 * These frames are intended for a read-only ESP32 dashboard/logger node. The
 * ESP32 must not be required for BMS_OK, charger control, ADBMS communication,
 * or any other safety output.
 */

#ifndef INC_EXT_DRIVERS_AMS_CAN_LOGGER_H_
#define INC_EXT_DRIVERS_AMS_CAN_LOGGER_H_

#include <stdint.h>

#define AMS_LOGGER_PROTOCOL_VERSION       1u

#define AMS_LOGGER_CAN_ID_HEARTBEAT       0x690u
#define AMS_LOGGER_CAN_ID_FAULT_REASONS   0x691u
#define AMS_LOGGER_CAN_ID_PACK_ELECTRICAL 0x692u
#define AMS_LOGGER_CAN_ID_TEMP_FAN        0x693u
#define AMS_LOGGER_CAN_ID_VOLTAGE_HEALTH  0x694u
#define AMS_LOGGER_CAN_ID_TEMP_HEALTH     0x695u
#define AMS_LOGGER_CAN_ID_CHARGER         0x696u
#define AMS_LOGGER_CAN_ID_CURRENT_DETAIL  0x697u
#define AMS_LOGGER_CAN_ID_6830_LINK       0x698u
#define AMS_LOGGER_CAN_ID_6830_COUNTERS   0x699u
#define AMS_LOGGER_CAN_ID_2950_LINK       0x69Au
#define AMS_LOGGER_CAN_ID_TASK_HEALTH     0x69Bu
#define AMS_LOGGER_CAN_ID_CAN_DIAG        0x69Cu
#define AMS_LOGGER_CAN_ID_SAFETY_DIAG     0x69Du
#define AMS_LOGGER_CAN_ID_WATCHDOG_DIAG   0x69Eu
#define AMS_LOGGER_CAN_ID_ADBMS_DIAG      0x69Fu

#define AMS_LOGGER_CAN_ID_CELL_DETAIL     0x6A0u
#define AMS_LOGGER_CAN_ID_TEMP_DETAIL     0x6A1u
#define AMS_LOGGER_CAN_ID_VOLTAGE_MASKS   0x6A2u
#define AMS_LOGGER_CAN_ID_TEMP_MASKS_A    0x6A3u
#define AMS_LOGGER_CAN_ID_TEMP_MASKS_B    0x6A4u
#define AMS_LOGGER_CAN_ID_VOLTAGE_PEC     0x6A5u
#define AMS_LOGGER_CAN_ID_CURRENT_ADC     0x6A6u
#define AMS_LOGGER_CAN_ID_CHARGER_DETAIL  0x6A7u

#define AMS_LOGGER_TEMP_INVALID_DECI_C    ((uint16_t)0x8000u)

typedef enum
{
    AMS_LOGGER_HEARTBEAT_FLAG_BMS_OK = 0,
    AMS_LOGGER_HEARTBEAT_FLAG_AIR_STATE,
    AMS_LOGGER_HEARTBEAT_FLAG_IMD_OK,
    AMS_LOGGER_HEARTBEAT_FLAG_HARD_FAULT,
    AMS_LOGGER_HEARTBEAT_FLAG_SOFT_FAULT,
    AMS_LOGGER_HEARTBEAT_FLAG_CHARGER_FAULT,
    AMS_LOGGER_HEARTBEAT_FLAG_CANBUS_FAULT,
    AMS_LOGGER_HEARTBEAT_FLAG_BMS_OUTPUT_INHIBIT
} ams_logger_heartbeat_flag_t;

typedef enum
{
    AMS_LOGGER_VALID_FLAG_VOLTAGE_VALID = 0,
    AMS_LOGGER_VALID_FLAG_CURRENT_VALID,
    AMS_LOGGER_VALID_FLAG_TEMP_VALID,
    AMS_LOGGER_VALID_FLAG_VOLTAGE_READ_FAULT,
    AMS_LOGGER_VALID_FLAG_TEMP_READ_FAULT,
    AMS_LOGGER_VALID_FLAG_CURRENT_SENSOR_FAULT,
    AMS_LOGGER_VALID_FLAG_VOLTAGE_LATCHED,
    AMS_LOGGER_VALID_FLAG_TEMP_LATCHED
} ams_logger_valid_flag_t;

typedef enum
{
    AMS_LOGGER_CURRENT_FLAG_FAULT = 0,
    AMS_LOGGER_CURRENT_FLAG_SENSOR_FAULT,
    AMS_LOGGER_CURRENT_FLAG_WARNING,
    AMS_LOGGER_CURRENT_FLAG_PENDING,
    AMS_LOGGER_CURRENT_FLAG_CONFIRMED,
    AMS_LOGGER_CURRENT_FLAG_LATCHED,
    AMS_LOGGER_CURRENT_FLAG_FUSE_FAULT,
    AMS_LOGGER_CURRENT_FLAG_ESTIMATOR_FAULT
} ams_logger_current_flag_t;


typedef enum
{
    AMS_LOGGER_SAFETY_FLAG_PANIC_ACTIVE = 0,
    AMS_LOGGER_SAFETY_FLAG_BMS_OUTPUT_INHIBIT,
    AMS_LOGGER_SAFETY_FLAG_BALANCE_INHIBIT,
    AMS_LOGGER_SAFETY_FLAG_BMS_STATE,
    AMS_LOGGER_SAFETY_FLAG_HARD_FAULT,
    AMS_LOGGER_SAFETY_FLAG_TASK_HEARTBEAT_FAULT,
    AMS_LOGGER_SAFETY_FLAG_LOGGER_HEARTBEAT_FAULT
} ams_logger_safety_flag_t;

typedef enum
{
    AMS_LOGGER_WATCHDOG_FLAG_RUNTIME_ENABLED = 0,
    AMS_LOGGER_WATCHDOG_FLAG_HW_STARTED,
    AMS_LOGGER_WATCHDOG_FLAG_FEED_GATE_OK
} ams_logger_watchdog_flag_t;

typedef enum
{
    AMS_LOGGER_ADBMS_DIAG_FLAG_DIAG_FAULT = 0,
    AMS_LOGGER_ADBMS_DIAG_FLAG_CONFIG_FAULT,
    AMS_LOGGER_ADBMS_DIAG_FLAG_STATUS_FAULT,
    AMS_LOGGER_ADBMS_DIAG_FLAG_OPEN_WIRE_FAULT,
    AMS_LOGGER_ADBMS_DIAG_FLAG_SCAN_ACTIVE,
    AMS_LOGGER_ADBMS_DIAG_FLAG_HIL_REPLACE
} ams_logger_adbms_diag_flag_t;

typedef enum
{
    AMS_LOGGER_HIL_FLAG_MEAS_FRESH = 0,
    AMS_LOGGER_HIL_FLAG_TRUTH_FRESH,
    AMS_LOGGER_HIL_FLAG_SUMMARY_FRESH
} ams_logger_hil_flag_t;


typedef enum
{
    AMS_LOGGER_CURRENT_ADC_FLAG_HIGH_FRESH = 0,
    AMS_LOGGER_CURRENT_ADC_FLAG_LOW_FRESH,
    AMS_LOGGER_CURRENT_ADC_FLAG_LAST_READ_OK,
    AMS_LOGGER_CURRENT_ADC_FLAG_CURRENT_VALID,
    AMS_LOGGER_CURRENT_ADC_FLAG_SENSOR_FAULT,
    AMS_LOGGER_CURRENT_ADC_FLAG_ZERO_CALIBRATED
} ams_logger_current_adc_flag_t;

typedef enum
{
    AMS_LOGGER_CHARGER_FLAG_HW_FAIL = 0,
    AMS_LOGGER_CHARGER_FLAG_OVERTEMP_FAIL,
    AMS_LOGGER_CHARGER_FLAG_INPUT_VOLT_FAIL,
    AMS_LOGGER_CHARGER_FLAG_VOLTAGE_SENSE_FAIL,
    AMS_LOGGER_CHARGER_FLAG_COMM_FAIL,
    AMS_LOGGER_CHARGER_FLAG_TEMP_CHARGE_STOP,
    AMS_LOGGER_CHARGER_FLAG_VOLTAGE_CHARGE_STOP,
    AMS_LOGGER_CHARGER_FLAG_DISABLE_CHARGE
} ams_logger_charger_flag_t;

#endif /* INC_EXT_DRIVERS_AMS_CAN_LOGGER_H_ */
