function acceptance = evaluate_validation_acceptance( ...
    report, acceptance_cfg, test_class)
%EVALUATE_VALIDATION_ACCEPTANCE Apply frozen numerical qualification gates.

limits = hil.validation_limits_at_temperature( ...
    acceptance_cfg, test_class, report.test_temperature_C);
checks = struct();
checks.minimum_comparable_samples = ...
    report.voltage_error.count >= acceptance_cfg.minimum_comparable_samples;
checks.rms_voltage_error = ...
    report.voltage_error.rms <= limits.rms_voltage_error_V;
checks.maximum_voltage_error = ...
    report.voltage_error.maximum_absolute <= limits.maximum_voltage_error_V;
checks.p95_voltage_error = ...
    report.voltage_error.p95_absolute <= limits.p95_voltage_error_V;
checks.absolute_mean_bias = ...
    abs(report.voltage_error.mean_bias) <= limits.absolute_mean_bias_V;
checks.endpoint_voltage_error = ...
    abs(report.endpoint_voltage_error_V) <= ...
    limits.endpoint_voltage_error_V;

have_temperature = ...
    report.surface_temperature_error.count >= ...
    acceptance_cfg.minimum_comparable_samples;
checks.surface_temperature_available = ...
    have_temperature || ~acceptance_cfg.require_surface_temperature;
checks.surface_temperature_rms_error = ...
    ~have_temperature || ...
    (report.surface_temperature_error.rms <= ...
     limits.surface_temperature_rms_error_C);
checks.surface_temperature_maximum_error = ...
    ~have_temperature || ...
    (report.surface_temperature_error.maximum_absolute <= ...
     limits.surface_temperature_maximum_error_C);

have_soc = report.soc_error.count >= 2 && ...
    isfinite(report.endpoint_soc_error);
checks.soc_reference_available = ...
    have_soc || ~acceptance_cfg.require_soc_reference;
checks.endpoint_soc_error = ...
    ~have_soc || ...
    (abs(report.endpoint_soc_error) <= ...
     limits.endpoint_soc_error_fraction);

if strcmpi(test_class, 'hppc')
    checks.minimum_pulses = report.pulse_count >= limits.minimum_pulses;
    checks.loaded_rms_voltage_error = ...
        report.loaded_voltage_error.rms <= ...
        limits.loaded_rms_voltage_error_V;
    checks.maximum_loaded_voltage_error = ...
        report.loaded_voltage_error.maximum_absolute <= ...
        limits.maximum_loaded_voltage_error_V;
    checks.relaxation_rms_voltage_error = ...
        report.relaxation_voltage_error.rms <= ...
        limits.relaxation_rms_voltage_error_V;
end

names = fieldnames(checks);
failed = names(~cellfun(@(name) checks.(name), names));
acceptance = struct( ...
    'passed', isempty(failed), ...
    'test_class', lower(char(test_class)), ...
    'configuration_id', acceptance_cfg.id, ...
    'limits', limits, ...
    'checks', checks, ...
    'failed_checks', {failed});
end
