function files = export_parameter_summary(params, output_directory)
%EXPORT_PARAMETER_SUMMARY Export reviewable ECM tables from a parameter package.

hil.ensure_directory(output_directory);
soc = double(params.soc_common(:));
temperature = double(params.temp_bp(:));
row_count = numel(soc) * numel(temperature);
rows = zeros(row_count, 10);
row = 0;
for temperature_index = 1:numel(temperature)
    for soc_index = 1:numel(soc)
        row = row + 1;
        ocv = interp1(double(params.soc_ocv_common(:)), ...
            double(params.OCV(:, temperature_index)), soc(soc_index), ...
            'linear');
        r0 = double(params.R0(soc_index, temperature_index));
        r1 = double(params.R1(soc_index, temperature_index));
        c1 = double(params.C1(soc_index, temperature_index));
        rows(row, :) = [ ...
            temperature(temperature_index), soc(soc_index), ocv, ...
            r0, r1, c1, r1 * c1, double(params.R2), ...
            double(params.C2), double(params.R2 * params.C2)];
    end
end

table_data = array2table(rows, 'VariableNames', { ...
    'temperature_C', 'soc', 'OCV_V', 'R0_ohm', 'R1_ohm', ...
    'C1_F', 'tau1_s', 'R2_ohm', 'C2_F', 'tau2_s'});
csv_file = fullfile(output_directory, 'ecm_parameter_summary.csv');
writetable(table_data, csv_file);

json_file = fullfile(output_directory, 'parameter_summary.json');
summary = struct( ...
    'schema_version', params.schema_version, ...
    'cell_id', params.cell_id, ...
    'configuration_hash', params.configuration_hash, ...
    'validity_domain', params.validity_domain, ...
    'source_manifest', params.source_manifest, ...
    'table_file', csv_file);
hil.write_json(json_file, summary);
files = struct('csv', csv_file, 'json', json_file);
end
