function files = export_codegen_parity_case( ...
    result, profile, output_directory, identity)
%EXPORT_CODEGEN_PARITY_CASE Export input and full expected output CSV files.

if nargin < 4
    identity = struct();
end
hil.ensure_directory(output_directory);
if numel(profile.time_s) ~= numel(result.time_s) || ...
        max(abs(double(profile.time_s(:)) - double(result.time_s(:)))) > 1e-9
    error('hil:codegen:ParitySampleAlignment', ...
        'Parity reference must store every input sample.');
end
if numel(profile.time_s) > 100000
    error('hil:codegen:ParityCaseTooLarge', ...
        'Parity cases are limited to 100000 samples.');
end

input_file = fullfile(output_directory, 'input_profile.csv');
reference_file = fullfile(output_directory, 'reference_output.csv');
instructions_file = fullfile(output_directory, 'README.txt');
manifest_file = fullfile(output_directory, 'parity_case.json');
writetable(table( ...
    double(profile.time_s(:)), ...
    double(profile.pack_current_A(:)), ...
    double(profile.ambient_temperature_C(:)), ...
    'VariableNames', {'time_s', 'I_pack_A', 'T_ambient_C'}), input_file);
write_result_csv(result, reference_file);
manifest = struct( ...
    'schema_version', 2, ...
    'reference_origin', 'configured_simulink_output', ...
    'input_file', input_file, ...
    'input_sha256', hil.file_sha256(input_file), ...
    'reference_file', reference_file, ...
    'reference_sha256', hil.file_sha256(reference_file), ...
    'initial_soc', result.simulation_configuration.initial_soc, ...
    'initial_temperature_C', ...
        result.pack_configuration.initial_temperature_C, ...
    'scalar_tolerance', 2e-4, ...
    'array_tolerance', 5e-4, ...
    'identity', identity);
hil.write_json(manifest_file, manifest);

instructions = sprintf([ ...
    'Build HiL/esp32_plant/tests, then run:\n\n' ...
    '  ./build/parity_runner "%s" %.9g %.9g > generated_output.csv\n\n' ...
    'In MATLAB:\n\n' ...
    '  reference = "%s";\n' ...
    '  candidate = "%s";\n' ...
    '  report = hil.validate_codegen_parity(reference, candidate);\n'], ...
    input_file, ...
    result.simulation_configuration.initial_soc, ...
    result.pack_configuration.initial_temperature_C, ...
    reference_file, ...
    fullfile(output_directory, 'generated_output.csv'));
write_text(instructions_file, instructions);
files = struct( ...
    'input', input_file, ...
    'reference', reference_file, ...
    'instructions', instructions_file, ...
    'manifest', manifest_file);
end

function write_result_csv(result, file_path)
data = table( ...
    double(result.time_s(:)), double(result.V_pack(:)), ...
    double(result.T_core(:)), double(result.T_surf(:)), ...
    double(result.SoC_true(:)), double(result.V_min(:)), ...
    double(result.V_max(:)), double(result.T_max(:)), ...
    double(result.T_avg(:)), ...
    'VariableNames', { ...
        'time_s', 'V_pack', 'T_core', 'T_surf', 'SoC_true', ...
        'V_min', 'V_max', 'T_max', 'T_avg'});
data = append_array(data, result.V_group, 'V_group');
data = append_array(data, result.V_segment, 'V_segment');
data = append_array(data, result.T_sensor, 'T_sensor');
data = append_array(data, result.SoC_group, 'SoC_group');
writetable(data, file_path);
end

function data = append_array(data, values, prefix)
for index = 1:size(values, 2)
    data.(sprintf('%s_%d', prefix, index)) = double(values(:, index));
end
end

function write_text(file_path, content)
file = fopen(file_path, 'w');
if file < 0
    error('hil:file:WriteFailed', 'Could not write %s.', file_path);
end
cleanup = onCleanup(@() fclose(file)); %#ok<NASGU>
fprintf(file, '%s', content);
end
