function artifact = generate_code(cell_cfg, pack_cfg, sim_cfg, params, varargin)
%GENERATE_CODE Configure, validate, and package an ERT plant for ESP32.

parser = inputParser();
parser.addParameter('OutputDirectory', '', @(x) ischar(x) || isstring(x));
parser.addParameter('InstallIntoEsp32', false, ...
    @(x) islogical(x) && isscalar(x));
parser.parse(varargin{:});
options = parser.Results;
[cell_cfg, ~] = hil.validate_configuration(cell_cfg);
[pack_cfg, ~] = hil.validate_configuration(pack_cfg);
[sim_cfg, ~] = hil.validate_configuration(sim_cfg);
pack_cfg = hil.derive_pack(cell_cfg, pack_cfg);
if strcmpi(pack_cfg.imbalance_model.mode, 'parameter_distributed')
    error('hil:codegen:DistributedPlantUnsupported', ...
        ['parameter_distributed code generation is blocked because the ' ...
         'embedded plant evolves one representative electrothermal state. ' ...
         'Use hil.run_reference for independently evolved group states.']);
end
if options.InstallIntoEsp32
    error('hil:codegen:UnsafeDirectInstall', ...
        ['Direct installation is disabled. Generate into staging, run ' ...
         'tools/qualify_generated_plant.py, and promote only after fresh ' ...
         'generated-C/Simulink parity passes.']);
end

coder_license = license('test', 'Real-Time_Workshop') || ...
    license('test', 'Simulink_Coder') || ...
    license('test', 'RTW_Embedded_Coder');
if exist('slbuild', 'file') ~= 2 || ...
        ~license('test', 'Simulink') || ~coder_license
    error('hil:codegen:CoderRequired', ...
        ['Code generation requires MATLAB, Simulink, and a licensed ' ...
         'Simulink/Embedded Coder installation.']);
end
if isfield(sim_cfg.fault_injection, 'enabled') && ...
        logical(sim_cfg.fault_injection.enabled)
    error('hil:codegen:FaultInjectionBoundary', ...
        ['Fault injection belongs in the HIL transport/harness and is not ' ...
         'embedded in the generated physical plant.']);
end

paths = hil.project_paths();
output_directory = char(options.OutputDirectory);
if isempty(output_directory)
    build_hash = hil.configuration_hash( ...
        cell_cfg, pack_cfg, sim_cfg, params.configuration_hash);
    directory_name = sprintf('der_plant_%s_%s_%s', ...
        path_token(cell_cfg.id), path_token(pack_cfg.id), build_hash(1:12));
    output_directory = fullfile(paths.codegen_root, directory_name);
end
hil.ensure_directory(output_directory);

reference_cfg = sim_cfg;
reference_cfg.engine = 'reference';
reference_cfg.output_decimation = 1;
reference_profile = hil.load_profile(reference_cfg, cell_cfg, pack_cfg);
reference_result = hil.run_reference( ...
    cell_cfg, pack_cfg, reference_cfg, params, reference_profile);
if ~isfield(cell_cfg, 'dataset_configuration') || ...
        isempty(cell_cfg.dataset_configuration)
    error('hil:codegen:DatasetValidationRequired', ...
        ['Release code generation requires a configured independent ' ...
         'electrical holdout dataset.']);
end
dataset_cfg = hil.config.dataset(cell_cfg.dataset_configuration);
acceptance_name = cell_cfg.id;
if isfield(cell_cfg, 'config_name')
    acceptance_name = cell_cfg.config_name;
end
acceptance_cfg = hil.config.acceptance(acceptance_name);
dataset_validation = hil.validate_dataset( ...
    cell_cfg, pack_cfg, dataset_cfg, params, acceptance_cfg);
if ~dataset_validation.passed
    error('hil:codegen:DatasetValidationFailed', ...
        'Independent electrical holdout validation did not pass.');
end
pre_codegen_validation = struct( ...
    'schema_version', 2, ...
    'dataset_electrical_holdout', dataset_validation, ...
    'pack_outputs', hil.validate_pack_outputs(reference_result, pack_cfg), ...
    'scaling', hil.validate_scaling( ...
        cell_cfg, pack_cfg, reference_cfg, params));

model_artifact = hil.configure_model( ...
    cell_cfg, pack_cfg, sim_cfg, params, ...
    'OutputDirectory', fullfile(output_directory, 'configured_model'));
parity_profile = resolved_current_profile(reference_profile, reference_result);
simulink_result = hil.run_simulink_profile( ...
    cell_cfg, pack_cfg, sim_cfg, params, parity_profile, ...
    'ModelArtifact', model_artifact);
pre_codegen_validation.simulink_outputs = ...
    hil.validate_pack_outputs(simulink_result, pack_cfg);
pre_codegen_validation.reference_to_simulink = ...
    hil.validate_codegen_parity( ...
        reference_result, simulink_result, ...
        'ScalarTolerance', 5e-3, 'ArrayTolerance', 2e-3);
pre_codegen_validation.passed = ...
    pre_codegen_validation.dataset_electrical_holdout.passed && ...
    pre_codegen_validation.pack_outputs.passed && ...
    pre_codegen_validation.scaling.passed && ...
    pre_codegen_validation.simulink_outputs.passed && ...
    pre_codegen_validation.reference_to_simulink.passed;
if ~pre_codegen_validation.passed
    error('hil:codegen:PreCodegenValidation', ...
        ['Reference, scaling, Simulink-output, or reference/Simulink ' ...
         'validation failed before code generation.']);
end
pre_codegen_validation.status = 'PASS';
pre_codegen_validation.configuration_hash = ...
    model_artifact.configuration_hash;
pre_codegen_validation.parameter_hash = model_artifact.parameter_hash;
identity = struct( ...
    'model_name', model_artifact.model_name, ...
    'configuration_hash', model_artifact.configuration_hash, ...
    'parameter_hash', model_artifact.parameter_hash, ...
    'cell_configuration_hash', ...
        model_artifact.cell_configuration_hash, ...
    'pack_configuration_hash', ...
        model_artifact.pack_configuration_hash, ...
    'simulation_configuration_hash', ...
        model_artifact.simulation_configuration_hash, ...
    'model_manifest_sha256', ...
        hil.file_sha256(model_artifact.manifest_file));
pre_codegen_validation.identity = identity;
pre_codegen_validation_file = fullfile( ...
    output_directory, 'pre_codegen_validation.json');
hil.write_json(pre_codegen_validation_file, pre_codegen_validation);
parity_files = hil.export_codegen_parity_case( ...
    simulink_result, parity_profile, ...
    fullfile(output_directory, 'parity'), identity);

model_name = model_artifact.model_name;
load_system(model_artifact.model_file);
cleanup = onCleanup(@() close_system(model_name, 0)); %#ok<NASGU>

set_param(model_name, 'SystemTargetFile', 'ert.tlc');
set_param(model_name, 'TargetLang', 'C');
set_if_available(model_name, 'TargetLangStandard', 'C99 (ISO)');
set_if_available(model_name, 'GenerateReport', 'on');
set_if_available(model_name, 'LaunchReport', 'off');
set_if_available(model_name, 'GenCodeOnly', 'on');
set_if_available(model_name, 'GenerateSampleERTMain', 'off');
set_if_available(model_name, 'MatFileLogging', 'off');
set_if_available(model_name, 'SupportNonFinite', 'off');
set_if_available(model_name, 'DefaultParameterBehavior', 'Inlined');
set_if_available(model_name, 'CombineOutputUpdateFcns', 'on');
set_if_available(model_name, 'IncludeMdlTerminateFcn', 'on');
set_if_available(model_name, 'MultiInstanceERTCode', 'off');
set_if_available(model_name, 'ProdHWDeviceType', ...
    'Generic->32-bit Embedded Processor');
set_if_available(model_name, 'CustomSymbolStrGlobalVar', '$R$N$M');
set_if_available(model_name, 'CustomSymbolStrFcn', '$R$N$M$F');
set_if_available(model_name, 'CustomSymbolStrType', '$N$R$M_T');
set_if_available(model_name, 'CustomSymbolStrModelFcn', '$R$N');

code_folder = fullfile(output_directory, 'ert');
cache_folder = fullfile(output_directory, 'slprj');
hil.ensure_directory(code_folder);
hil.ensure_directory(cache_folder);
previous_control = Simulink.fileGenControl('getConfig');
restore_control = onCleanup(@() Simulink.fileGenControl( ...
    'setConfig', 'config', previous_control)); %#ok<NASGU>
Simulink.fileGenControl('set', ...
    'CodeGenFolder', code_folder, ...
    'CacheFolder', cache_folder, ...
    'createDir', true);

save_system(model_name);
log_file = fullfile(output_directory, 'codegen.log');
try
    build_log = evalc('slbuild(model_name);');
    write_text(log_file, build_log);
catch exception
    build_log = evalc('disp(getReport(exception, ''extended''));');
    write_text(log_file, build_log);
    rethrow(exception);
end
generated_directory = locate_generated_directory(code_folder, model_name);
esp32_package = hil.package_codegen_for_esp32( ...
    generated_directory, model_name, pack_cfg, model_artifact, ...
    fullfile(output_directory, 'esp32_component'));

source_manifest_repository_file = fullfile(paths.hil_root, ...
    'SOURCE_MANIFEST.json');
if ~isfile(source_manifest_repository_file)
    error('hil:codegen:SourceManifestMissing', ...
        'Missing checked-in source manifest: %s', ...
        source_manifest_repository_file);
end
source_manifest_file = fullfile(output_directory, 'source_manifest.json');
copyfile(source_manifest_repository_file, source_manifest_file, 'f');
component_manifest_file = fullfile( ...
    esp32_package, 'component_manifest.json');
artifact_file = fullfile(output_directory, 'codegen_artifact.json');
artifact = struct( ...
    'schema_version', 2, ...
    'artifact_root', output_directory, ...
    'identity', identity, ...
    'model', model_artifact, ...
    'model_manifest_file', model_artifact.manifest_file, ...
    'generated_directory', generated_directory, ...
    'esp32_component_directory', esp32_package, ...
    'component_manifest_file', component_manifest_file, ...
    'installed_into_esp32', false, ...
    'pre_codegen_validation_file', pre_codegen_validation_file, ...
    'parity_files', parity_files, ...
    'source_manifest_file', source_manifest_file, ...
    'source_manifest_sha256', hil.file_sha256(source_manifest_file), ...
    'codegen_log_file', log_file, ...
    'repository_commit', repository_commit(paths.repo_root), ...
    'matlab_version', version, ...
    'simulink_version', toolbox_version('Simulink'), ...
    'simulink_coder_version', toolbox_version('Simulink Coder'), ...
    'artifact_file', artifact_file);
hil.write_json(artifact_file, artifact);
end

function profile = resolved_current_profile(profile, reference_result)
% Freeze profile-layer bias/power resolution before Simulink/C comparison.
if numel(profile.time_s) ~= numel(reference_result.time_s) || ...
        max(abs(double(profile.time_s(:)) - ...
        double(reference_result.time_s(:)))) > 1e-9
    error('hil:codegen:ResolvedCurrentAlignment', ...
        'Reference output must contain every profile sample for code generation.');
end
profile.pack_current_A = double(reference_result.I_pack(:));
if isfield(profile, 'pack_power_W')
    profile = rmfield(profile, 'pack_power_W');
end
profile.scaling_mode = 'resolved_current';
profile.inputs_resolved = true;
end

function set_if_available(model_name, parameter, value)
try
    get_param(model_name, parameter);
    set_param(model_name, parameter, value);
catch exception
    warning('hil:codegen:ParameterUnavailable', ...
        'Skipping code-generation setting %s: %s', ...
        parameter, exception.message);
end
end

function generated_directory = locate_generated_directory(root, model_name)
candidates = dir(fullfile(root, '**', [model_name, '.h']));
if isempty(candidates)
    error('hil:codegen:HeaderMissing', ...
        'Could not find generated header %s.h under %s.', model_name, root);
end
paths = fullfile({candidates.folder}, {candidates.name});
[~, index] = min(cellfun(@strlength, paths));
generated_directory = candidates(index).folder;
end

function value = path_token(value)
value = lower(regexprep(char(value), '[^A-Za-z0-9_-]', '_'));
end

function value = toolbox_version(name)
items = ver;
match = find(strcmpi({items.Name}, name), 1, 'first');
if isempty(match)
    value = 'not installed';
else
    value = items(match).Version;
end
end

function commit = repository_commit(repo_root)
command = sprintf('git -C "%s" rev-parse HEAD', ...
    strrep(char(repo_root), '"', '\"'));
[status, output] = system(command);
if status == 0
    commit = strtrim(output);
else
    commit = 'unknown';
end
end

function write_text(file_path, content)
file = fopen(file_path, 'w');
if file < 0
    error('hil:file:WriteFailed', 'Could not write %s.', file_path);
end
cleanup = onCleanup(@() fclose(file)); %#ok<NASGU>
fprintf(file, '%s', content);
end
