function destination = package_codegen_for_esp32( ...
    generated_directory, model_name, pack_cfg, model_artifact, destination)
%PACKAGE_CODEGEN_FOR_ESP32 Create a self-contained ESP-IDF component.

[pack_cfg, ~] = hil.validate_configuration(pack_cfg);
paths = hil.project_paths();
hil.ensure_directory(destination);

search_root = fileparts(generated_directory);
files = [ ...
    dir(fullfile(generated_directory, '*.c')); ...
    dir(fullfile(generated_directory, '*.h')); ...
    dir(fullfile(search_root, '**', '*.c')); ...
    dir(fullfile(search_root, '**', '*.h'))];
if isempty(files)
    error('hil:codegen:NoFiles', ...
        'No generated C sources were found in %s.', generated_directory);
end

copied = {};
copied_sources = {};
for index = 1:numel(files)
    source = fullfile(files(index).folder, files(index).name);
    if strcmpi(files(index).name, 'ert_main.c') || ...
            any(strcmp(copied_sources, source))
        continue;
    end
    duplicate = find(strcmp(copied, files(index).name), 1, 'first');
    if ~isempty(duplicate)
        previous = copied_sources{duplicate};
        if ~strcmp(hil.file_sha256(previous), hil.file_sha256(source))
            error('hil:codegen:FlattenCollision', ...
                'Generated files named %s have different contents.', ...
                files(index).name);
        end
        continue;
    end
    copyfile(source, fullfile(destination, files(index).name), 'f');
    copied{end + 1, 1} = files(index).name; %#ok<AGROW>
    copied_sources{end + 1, 1} = source; %#ok<AGROW>
end

interface_files = { ...
    'plant_model_adapter.c', ...
    'plant_model_adapter.h'};
component_source = fullfile(paths.esp32_plant, 'components', 'plant_model');
for index = 1:numel(interface_files)
    copyfile(fullfile(component_source, interface_files{index}), ...
        fullfile(destination, interface_files{index}), 'f');
end

hil.write_esp32_interface_files( ...
    destination, model_name, pack_cfg, model_artifact);

c_sources = unique([ ...
    copied(endsWith(copied, '.c')); ...
    {'plant_model_adapter.c'}]);
cmake_lines = {'idf_component_register('; '    SRCS'};
for index = 1:numel(c_sources)
    cmake_lines{end + 1, 1} = sprintf('        "%s"', c_sources{index}); %#ok<AGROW>
end
cmake_lines = [cmake_lines; {'    INCLUDE_DIRS "."'; ')'}];
write_text(fullfile(destination, 'CMakeLists.txt'), ...
    strjoin(cmake_lines, newline));
make_lines = {'PLANT_MODEL_SOURCE_FILES := \'};
for index = 1:numel(c_sources)
    suffix = ' \';
    if index == numel(c_sources)
        suffix = '';
    end
    make_lines{end + 1, 1} = sprintf('\t%s%s', c_sources{index}, suffix); %#ok<AGROW>
end
write_text(fullfile(destination, 'plant_model_sources.mk'), ...
    strjoin(make_lines, newline));

manifest_file = fullfile(destination, 'component_manifest.json');
manifest_files = sort([copied; interface_files(:); ...
    {'plant_model_binding.h'; 'plant_model_manifest.h'; ...
     'plant_model_sources.mk'; 'CMakeLists.txt'}]);
file_records = repmat(struct('path', '', 'sha256', ''), ...
    numel(manifest_files), 1);
for index = 1:numel(manifest_files)
    file_records(index).path = manifest_files{index};
    file_records(index).sha256 = hil.file_sha256( ...
        fullfile(destination, manifest_files{index}));
end
manifest = struct( ...
    'schema_version', 2, ...
    'model_name', model_name, ...
    'configuration_hash', model_artifact.configuration_hash, ...
    'parameter_hash', model_artifact.parameter_hash, ...
    'cell_configuration_hash', ...
        model_artifact.cell_configuration_hash, ...
    'pack_configuration_hash', ...
        model_artifact.pack_configuration_hash, ...
    'simulation_configuration_hash', ...
        model_artifact.simulation_configuration_hash, ...
    'model_manifest_sha256', hil.file_sha256(model_artifact.manifest_file), ...
    'model_artifact', model_artifact, ...
    'pack_configuration', pack_cfg, ...
    'files', {manifest_files}, ...
    'file_records', file_records);
hil.write_json(manifest_file, manifest);
end

function write_text(file_path, content)
file = fopen(file_path, 'w');
if file < 0
    error('hil:file:WriteFailed', 'Could not write %s.', file_path);
end
cleanup = onCleanup(@() fclose(file)); %#ok<NASGU>
fprintf(file, '%s\n', content);
end
