function report = thermal_scenarios(cell_cfg, pack_cfg, sim_cfg, params)
%THERMAL_SCENARIOS Run cooling, hot-ambient, heat-soak, and weak-group screens.

base_profile = hil.load_profile(sim_cfg, cell_cfg, pack_cfg);
load_end_time_s = base_profile.time_s(end);
cooldown_duration_s = 600.0;
definitions = scenario_definitions(pack_cfg);
rows = repmat(empty_row(), numel(definitions), 1);

for scenario_index = 1:numel(definitions)
    definition = definitions(scenario_index);
    scenario_pack = definition.pack;
    scenario_pack.initial_temperature_C = definition.ambient_temperature_C;
    scenario_sim = sim_cfg;
    scenario_sim.ambient_temperature_C = definition.ambient_temperature_C;
    scenario_sim.engine = 'reference';
    profile = append_cooldown( ...
        base_profile, definition.ambient_temperature_C, cooldown_duration_s);
    result = hil.run_reference( ...
        cell_cfg, scenario_pack, scenario_sim, params, profile);
    thermal = hil.validate_thermal(result, scenario_pack);
    rows(scenario_index) = summarize( ...
        definition, result, thermal, pack_cfg, load_end_time_s);
end

scenarios = struct2table(rows);
optimistic = scenarios.peak_core_temperature_C( ...
    strcmp(scenarios.scenario, 'natural_convection_optimistic'));
nominal = scenarios.peak_core_temperature_C( ...
    strcmp(scenarios.scenario, 'natural_convection_nominal'));
conservative = scenarios.peak_core_temperature_C( ...
    strcmp(scenarios.scenario, 'natural_convection_conservative'));
hot = scenarios.peak_core_temperature_C( ...
    strcmp(scenarios.scenario, 'hot_ambient_nominal'));

checks = struct();
core_metrics = scenarios{:, { ...
    'temperature_after_repeated_cycles_C', ...
    'final_core_temperature_C', ...
    'peak_core_temperature_C', ...
    'peak_surface_temperature_C', ...
    'peak_sensor_temperature_C', ...
    'maximum_core_surface_delta_C', ...
    'time_above_40C_s', 'time_above_50C_s', 'time_above_60C_s'}};
checks.all_outputs_finite = all(isfinite(core_metrics), 'all');
checks.conservative_cooling_not_better = conservative + 1e-6 >= optimistic;
checks.hot_ambient_not_cooler = hot + 1e-6 >= nominal;
checks.cooldown_cases_executed = all( ...
    scenarios.cooldown_observation_s >= cooldown_duration_s - 1e-6);
names = fieldnames(checks);
failed = names(~cellfun(@(name) checks.(name), names));

report = struct();
report.passed = isempty(failed);
report.checks = checks;
report.failed_checks = failed;
report.scenarios = scenarios;
report.load_profile = base_profile.name;
report.load_end_time_s = load_end_time_s;
report.cooldown_duration_s = cooldown_duration_s;
report.interpretation = ...
    ['Comparative sensitivity only. These cases do not prove fanless ' ...
     'acceptability because geometry, module conduction, busbar heating, ' ...
     'enclosure convection, and airflow are not calibrated.'];
end

function definitions = scenario_definitions(pack_cfg)
definitions = repmat(struct( ...
    'name', '', 'pack', pack_cfg, 'ambient_temperature_C', 25.0, ...
    'weak_group_index', 0), 6, 1);

definitions(1) = make_definition( ...
    'natural_convection_optimistic', pack_cfg, 0.70, 25.0, 'uniform', 0);
definitions(2) = make_definition( ...
    'natural_convection_nominal', pack_cfg, 1.00, 25.0, 'uniform', 0);
definitions(3) = make_definition( ...
    'natural_convection_conservative', pack_cfg, 1.50, 25.0, 'uniform', 0);
definitions(4) = make_definition( ...
    'hot_ambient_nominal', pack_cfg, 1.00, 40.0, 'uniform', 0);
definitions(5) = make_definition( ...
    'unequal_thermal_resistance', pack_cfg, 1.00, 40.0, ...
    'parameter_distributed', 0);

weak_group = ceil(double(pack_cfg.series_groups) / 2);
weak = make_definition( ...
    'weak_high_resistance_group', pack_cfg, 1.00, 40.0, ...
    'parameter_distributed', weak_group);
weak.pack.imbalance_model.overrides = struct( ...
    'group_index', weak_group, ...
    'capacity_multiplier', 0.95, ...
    'r0_multiplier', 1.25, ...
    'r1_multiplier', 1.15, ...
    'r2_multiplier', 1.15, ...
    'rsa_multiplier', 1.50, ...
    'initial_soc_offset', -0.005);
definitions(6) = weak;
end

function definition = make_definition( ...
    name, pack_cfg, rsa_multiplier, ambient, mode, weak_group)
pack_cfg.cooling_boundary.Rsa_multiplier = rsa_multiplier;
pack_cfg.imbalance_model.mode = mode;
definition = struct( ...
    'name', name, ...
    'pack', pack_cfg, ...
    'ambient_temperature_C', ambient, ...
    'weak_group_index', weak_group);
end

function profile = append_cooldown(profile, ambient, duration_s)
sample_time = double(profile.sample_time_s);
rest_count = max(1, round(double(duration_s) / sample_time));
rest_time = profile.time_s(end) + sample_time * (1:rest_count).';
profile.time_s = [profile.time_s; rest_time];
profile.pack_current_A = [profile.pack_current_A; zeros(rest_count, 1)];
profile.ambient_temperature_C = [ ...
    repmat(double(ambient), numel(profile.ambient_temperature_C), 1); ...
    repmat(double(ambient), rest_count, 1)];
if isfield(profile, 'pack_power_W')
    profile.pack_power_W = [profile.pack_power_W; zeros(rest_count, 1)];
end
profile.name = [profile.name, '_with_heat_soak'];
end

function row = summarize(definition, result, thermal, pack_cfg, load_end_time)
load_index = find(result.time_s <= load_end_time + 1e-9, 1, 'last');
[~, peak_linear] = max(result.T_sensor(:));
[~, peak_sensor] = ind2sub(size(result.T_sensor), peak_linear);
peak_group = pack_cfg.temp_sensor_to_group(peak_sensor);
cooldown_mask = result.time_s >= load_end_time;
cooldown_time = result.time_s(cooldown_mask);
cooldown_core = result.T_core(cooldown_mask);
cooled = find(cooldown_core <= definition.ambient_temperature_C + 2.0, ...
    1, 'first');
if isempty(cooled)
    cooldown_to_plus_2 = NaN;
else
    cooldown_to_plus_2 = cooldown_time(cooled) - load_end_time;
end

row = empty_row();
row.scenario = definition.name;
row.Rsa_multiplier = definition.pack.cooling_boundary.Rsa_multiplier;
row.ambient_temperature_C = definition.ambient_temperature_C;
row.imbalance_mode = definition.pack.imbalance_model.mode;
row.weak_group_index = definition.weak_group_index;
row.temperature_after_repeated_cycles_C = result.T_core(load_index);
row.final_core_temperature_C = thermal.final_core_temperature_C;
row.peak_core_temperature_C = thermal.peak_core_temperature_C;
row.peak_surface_temperature_C = thermal.peak_surface_temperature_C;
row.peak_sensor_temperature_C = thermal.peak_sensor_temperature_C;
row.maximum_core_surface_delta_C = thermal.maximum_core_surface_delta_C;
row.hottest_sensor_index = peak_sensor;
row.hottest_group_index = peak_group;
row.time_above_40C_s = time_above(result.time_s, result.T_sensor, 40.0);
row.time_above_50C_s = time_above(result.time_s, result.T_sensor, 50.0);
row.time_above_60C_s = time_above(result.time_s, result.T_sensor, 60.0);
row.cooldown_to_ambient_plus_2C_s = cooldown_to_plus_2;
row.cooldown_observation_s = result.time_s(end) - load_end_time;
end

function duration = time_above(time, temperature, threshold)
mask = max(double(temperature), [], 2) > threshold;
duration = sum(diff(double(time(:))) .* double(mask(1:end - 1)));
end

function value = empty_row()
value = struct( ...
    'scenario', '', ...
    'Rsa_multiplier', NaN, ...
    'ambient_temperature_C', NaN, ...
    'imbalance_mode', '', ...
    'weak_group_index', NaN, ...
    'temperature_after_repeated_cycles_C', NaN, ...
    'final_core_temperature_C', NaN, ...
    'peak_core_temperature_C', NaN, ...
    'peak_surface_temperature_C', NaN, ...
    'peak_sensor_temperature_C', NaN, ...
    'maximum_core_surface_delta_C', NaN, ...
    'hottest_sensor_index', NaN, ...
    'hottest_group_index', NaN, ...
    'time_above_40C_s', NaN, ...
    'time_above_50C_s', NaN, ...
    'time_above_60C_s', NaN, ...
    'cooldown_to_ambient_plus_2C_s', NaN, ...
    'cooldown_observation_s', NaN);
end
