function report = validate_all(varargin)
%VALIDATE_ALL Run framework gates and report qualification gaps explicitly.
%
% The legacy report.passed field means that all executed/required framework
% gates passed. It does not mean that generated C, ESP-IDF, or hardware were
% qualified. Use qualification_complete and the gate status table instead.

parser = inputParser();
parser.addParameter('OutputDirectory', '', @(x) ischar(x) || isstring(x));
parser.addParameter('RunThermal', true, ...
    @(x) islogical(x) && isscalar(x));
parser.addParameter('RunDataset', 'auto', ...
    @(x) ischar(x) || isstring(x) || (islogical(x) && isscalar(x)));
parser.addParameter('RequireDataset', false, ...
    @(x) islogical(x) && isscalar(x));
parser.addParameter('RunSimulink', 'auto', ...
    @(x) ischar(x) || isstring(x) || (islogical(x) && isscalar(x)));
parser.parse(varargin{:});
options = parser.Results;

paths = hil.project_paths();
output_directory = char(options.OutputDirectory);
if isempty(output_directory)
    output_directory = fullfile(paths.output_root, 'full_validation');
end
hil.ensure_directory(output_directory);

cell_cfg = hil.config.cell('p42a');
pack_cfg = hil.config.pack('der26_75s6p');
structural_pack = hil.config.pack('structural_12s2p');
sim_cfg = hil.config.simulation('hppc_validation');
dataset_cfg = hil.config.dataset('p42a_published_hcgt');
acceptance_cfg = hil.config.acceptance('p42a');
[params, build_report] = hil.build_parameters(cell_cfg, 'Save', false);
parameter_validation = hil.validate_parameters(cell_cfg, params);

primary_result = hil.run_profile(cell_cfg, pack_cfg, sim_cfg, params);
primary_pack_outputs = hil.validate_pack_outputs(primary_result, pack_cfg);
primary_scaling = hil.validate_scaling(cell_cfg, pack_cfg, sim_cfg, params);

structural_sim = sim_cfg;
structural_sim.id = 'structural_12s2p_validation';
structural_sim.stop_time_s = 30.0;
structural_sim.initial_soc = structural_pack.initial_soc;
structural_sim.engine = 'reference';
structural_result = hil.run_profile( ...
    cell_cfg, structural_pack, structural_sim, params);
structural_pack_outputs = hil.validate_pack_outputs( ...
    structural_result, structural_pack);
structural_scaling = hil.validate_scaling( ...
    cell_cfg, structural_pack, structural_sim, params);
thermal_physics = hil.validate_thermal_physics( ...
    cell_cfg, pack_cfg, sim_cfg, params);

report = struct();
report.schema_version = 2;
report.generated_utc = char(datetime('now', 'TimeZone', 'UTC', ...
    'Format', 'yyyy-MM-dd''T''HH:mm:ssXXX'));
report.cell_configuration = cell_cfg.id;
report.pack_configuration = pack_cfg.id;
report.parameter_source = build_report.mode;
report.parameter_hash = params.configuration_hash;
report.parameter_validation = parameter_validation;
report.acceptance_configuration = ...
    hil.validate_acceptance_configuration(acceptance_cfg);
report.dataset_contract = validate_normalization_contract();
report.primary_pack_outputs = primary_pack_outputs;
report.primary_scaling = primary_scaling;
report.structural_pack_outputs = structural_pack_outputs;
report.structural_scaling = structural_scaling;
report.thermal_physics = thermal_physics;

if options.RunThermal
    thermal_cfg = hil.config.simulation('thermal_endurance');
    thermal_cfg.engine = 'reference';
    report.thermal_screening = hil.thermal_scenarios( ...
        cell_cfg, pack_cfg, thermal_cfg, params);
end

static_passed = parameter_validation.passed && ...
    report.acceptance_configuration.passed && ...
    report.dataset_contract.passed;
invariant_passed = primary_pack_outputs.passed && ...
    primary_scaling.passed && structural_pack_outputs.passed && ...
    structural_scaling.passed && thermal_physics.passed;
if isfield(report, 'thermal_screening')
    invariant_passed = invariant_passed && report.thermal_screening.passed;
end
report.gates = struct();
report.gates.static_configuration = make_gate( ...
    pass_status(static_passed), true, ...
    'Configuration, parameter, and acceptance-rule checks.', struct());
report.gates.model_invariants = make_gate( ...
    pass_status(invariant_passed), true, ...
    '75s6p and 12s2p reference-model invariants and scaling.', struct());

[run_dataset, dataset_required] = resolve_optional_gate( ...
    options.RunDataset, options.RequireDataset, ...
    p42a_data_available(dataset_cfg), 'RunDataset');
if run_dataset
    try
        report.dataset_validation = hil.validate_dataset( ...
            cell_cfg, pack_cfg, dataset_cfg, params, acceptance_cfg);
        report.gates.p42a_dataset_validation = make_gate( ...
            pass_status(report.dataset_validation.passed), ...
            dataset_required, ...
            ['Electrical holdout uses cells A15/A19/A21/A37; thermal ' ...
             'validation is separately reported and may be NOT_RUN.'], ...
            report.dataset_validation);
    catch dataset_error
        report.gates.p42a_dataset_validation = make_gate( ...
            'FAIL', dataset_required, ...
            sprintf('%s: %s', dataset_error.identifier, dataset_error.message), ...
            struct());
    end
else
    report.gates.p42a_dataset_validation = make_gate( ...
        'NOT_RUN', dataset_required, ...
        ['P42A raw data was not available below HIL_DATA_ROOT. Supply the ' ...
         'external dataset to execute the numerical electrical holdout.'], ...
        struct());
end

[run_simulink, simulink_required] = resolve_optional_gate( ...
    options.RunSimulink, false, simulink_available(), 'RunSimulink');
if islogical(options.RunSimulink) && options.RunSimulink
    simulink_required = true;
end
if run_simulink
    try
        simulink_cfg = sim_cfg;
        simulink_cfg.engine = 'simulink';
        simulink_result = hil.run_profile( ...
            cell_cfg, pack_cfg, simulink_cfg, params);
        report.simulink_outputs = hil.validate_pack_outputs( ...
            simulink_result, pack_cfg);
        report.simulink_parity = hil.validate_codegen_parity( ...
            primary_result, simulink_result, ...
            'ScalarTolerance', 5e-3, 'ArrayTolerance', 1e-3);
        simulink_passed = report.simulink_outputs.passed && ...
            report.simulink_parity.passed;
        report.gates.simulink_execution = make_gate( ...
            pass_status(simulink_passed), simulink_required, ...
            'Configured Simulink execution and reference parity.', ...
            report.simulink_parity);
    catch simulink_error
        report.gates.simulink_execution = make_gate( ...
            'FAIL', simulink_required, ...
            sprintf('%s: %s', ...
                simulink_error.identifier, simulink_error.message), struct());
    end
else
    report.gates.simulink_execution = make_gate( ...
        'NOT_RUN', simulink_required, ...
        'MATLAB Simulink execution was unavailable or not requested.', struct());
end

report.gates.generated_c_parity = make_gate( ...
    'NOT_RUN', false, ...
    ['Run generate_esp32_plant and the strict staged qualifier; this ' ...
     'MATLAB framework report does not infer generated-C evidence.'], struct());
report.gates.esp_idf_build = make_gate( ...
    'NOT_RUN', false, ...
    'Run the staged ESP-IDF build before generated-code promotion.', struct());
report.gates.hardware_qualification = make_gate( ...
    'NOT_RUN', false, ...
    'Requires the ESP32/MCP2515 and physical AMS qualification bench.', struct());

gate_names = fieldnames(report.gates);
executed_or_required_pass = true;
all_qualification_pass = true;
all_qualification_complete = true;
for index = 1:numel(gate_names)
    item = report.gates.(gate_names{index});
    executed_or_required_pass = executed_or_required_pass && ...
        ~strcmp(item.status, 'FAIL') && ...
        (~item.required || strcmp(item.status, 'PASS'));
    all_qualification_pass = all_qualification_pass && ...
        strcmp(item.status, 'PASS');
    all_qualification_complete = all_qualification_complete && ...
        ~strcmp(item.status, 'NOT_RUN');
end
report.framework_passed = executed_or_required_pass;
report.qualification_complete = all_qualification_complete;
report.qualification_passed = ...
    all_qualification_complete && all_qualification_pass;
report.passed = report.framework_passed;

report.parameter_summary_files = hil.export_parameter_summary( ...
    params, fullfile(output_directory, 'parameters'));
report.primary_result_files = hil.export_report( ...
    primary_result, fullfile(output_directory, 'primary_75s6p'));
report.structural_result_files = hil.export_report( ...
    structural_result, fullfile(output_directory, 'structural_12s2p'));
report.report_files = hil.export_validation_report(report, output_directory);
save(fullfile(output_directory, 'validation_workspace.mat'), ...
    'report', 'primary_result', 'structural_result', '-v7');

if ~report.framework_passed
    error('hil:validation:FullSuite', ...
        'One or more executed or required HIL framework gates failed.');
end
end

function [run_gate, required] = resolve_optional_gate( ...
        requested, required, available, option_name)
if islogical(requested)
    run_gate = requested;
    required = required || requested;
    return;
end
if ~strcmpi(char(requested), 'auto')
    error('hil:validation:GateOption', ...
        '%s must be true, false, or "auto".', option_name);
end
run_gate = available;
end

function available = p42a_data_available(dataset_cfg)
available = false;
for index = 1:numel(dataset_cfg.root_candidates)
    candidate = fullfile( ...
        dataset_cfg.root, dataset_cfg.root_candidates{index}, 'phase_2');
    if exist(candidate, 'dir') == 7
        available = true;
        return;
    end
end
end

function available = simulink_available()
available = exist('sim', 'file') == 2 && license('test', 'Simulink');
end

function value = pass_status(passed)
if passed
    value = 'PASS';
else
    value = 'FAIL';
end
end

function value = make_gate(status, required, reason, evidence)
value = struct( ...
    'status', upper(char(status)), ...
    'required', logical(required), ...
    'reason', char(reason), ...
    'evidence', evidence);
end

function report = validate_normalization_contract()
raw = struct( ...
    'time_s', [102; 100; 101], ...
    'cell_current_A', [0; 0; 1], ...
    'cell_voltage_V', [4.18; 4.20; 4.19], ...
    'surface_temperature_C', [NaN; NaN; NaN], ...
    'surface_temperature_source', 'not_available', ...
    'ambient_temperature_C', [25; 25; 25], ...
    'initial_soc', 0.75, ...
    'initial_ocv_V', 4.05, ...
    'pulse_soc', 0.75, ...
    'soc_source', 'synthetic contract test', ...
    'source_file', 'synthetic');
[tests, normalization] = hil.normalize_dataset(raw, struct( ...
    'current_sign', 'positive_discharge'));
checks = struct();
checks.one_record_accepted = ...
    numel(tests) == 1 && normalization.accepted_record_count == 1;
checks.zero_time_origin = checks.one_record_accepted && ...
    abs(tests(1).time_s(1)) <= 1e-12;
checks.strictly_increasing_time = checks.one_record_accepted && ...
    all(diff(tests(1).time_s) > 0);
checks.initial_soc_preserved = checks.one_record_accepted && ...
    abs(tests(1).initial_soc - 0.75) <= 1e-12;
checks.initial_ocv_preserved = checks.one_record_accepted && ...
    abs(tests(1).initial_ocv_V - 4.05) <= 1e-12;
checks.ambient_not_surface = checks.one_record_accepted && ...
    ~any(isfinite(tests(1).surface_temperature_C)) && ...
    strcmp(tests(1).surface_temperature_source, 'not_available');
names = fieldnames(checks);
failed = names(~cellfun(@(name) checks.(name), names));
report = struct( ...
    'passed', isempty(failed), ...
    'checks', checks, ...
    'failed_checks', {failed}, ...
    'normalization_report', normalization);
end
