function report = validate_scaling(cell_cfg, pack_cfg, sim_cfg, params)
%VALIDATE_SCALING Guard Ns/Np, coulomb counting, and sample-time semantics.

pack_cfg.imbalance_model.mode = 'uniform';
sim_cfg.engine = 'reference';
sim_cfg.stop_time_s = 20.0;
sim_cfg.initial_soc = min(0.80, pack_cfg.initial_soc);
current_A = 0.5 * double(pack_cfg.parallel_cells) * ...
    double(cell_cfg.nominal_capacity_Ah);
time_s = (0:double(sim_cfg.sample_time_s):double(sim_cfg.stop_time_s)).';
profile = struct( ...
    'time_s', time_s, ...
    'pack_current_A', repmat(current_A, size(time_s)), ...
    'ambient_temperature_C', ...
        repmat(double(sim_cfg.ambient_temperature_C), size(time_s)), ...
    'name', 'scaling_guard', ...
    'source', 'hil.validate_scaling', ...
    'sample_time_s', double(sim_cfg.sample_time_s), ...
    'repeat_policy', 'one_shot', ...
    'scaling_mode', 'no_scaling');
result = hil.run_reference(cell_cfg, pack_cfg, sim_cfg, params, profile);

expected_cell_current = current_A / double(pack_cfg.parallel_cells);
integrated_intervals = numel(time_s) - 1;
expected_soc = double(sim_cfg.initial_soc) - ...
    integrated_intervals * double(sim_cfg.sample_time_s) * ...
    expected_cell_current / ...
    (3600 * double(cell_cfg.nominal_capacity_Ah));
actual_soc = double(result.SoC_true(end));
soc_error = actual_soc - expected_soc;

pack_report = hil.validate_pack_outputs(result, pack_cfg, ...
    'ThrowOnFailure', false);
dt = diff(result.time_s);
sample_time_error = max(abs(dt - double(sim_cfg.sample_time_s)));

checks = struct();
checks.pack_current_to_cell_current = ...
    abs(expected_cell_current - 0.5 * cell_cfg.nominal_capacity_Ah) < 1e-12;
checks.coulomb_count = abs(soc_error) < 2e-9;
checks.sample_time_applied_once = sample_time_error < 1e-10;
checks.pack_voltage_scales_with_Ns = pack_report.checks.pack_voltage_conserved;
checks.outputs_structurally_valid = pack_report.passed;

names = fieldnames(checks);
failed = names(~cellfun(@(name) checks.(name), names));
report = struct( ...
    'passed', isempty(failed), ...
    'checks', checks, ...
    'failed_checks', {failed}, ...
    'expected_cell_current_A', expected_cell_current, ...
    'expected_final_soc', expected_soc, ...
    'actual_final_soc', actual_soc, ...
    'soc_error', soc_error, ...
    'maximum_sample_time_error_s', sample_time_error, ...
    'pack_output_report', pack_report);
if ~report.passed
    error('hil:validation:Scaling', ...
        'Scaling validation failed: %s', strjoin(failed, ', '));
end
end
