function report = validate_acceptance_configuration(acceptance_cfg)
%VALIDATE_ACCEPTANCE_CONFIGURATION Exercise PASS/FAIL semantics without data.

[acceptance_cfg, ~] = hil.validate_configuration(acceptance_cfg);
limits = hil.validation_limits_at_temperature( ...
    acceptance_cfg, 'hppc', 25);

nominal = struct();
nominal.test_temperature_C = 25;
nominal.voltage_error = metric( ...
    acceptance_cfg.minimum_comparable_samples, ...
    0.5 * limits.rms_voltage_error_V, ...
    0.5 * limits.maximum_voltage_error_V, ...
    0.5 * limits.p95_voltage_error_V, ...
    0.5 * limits.absolute_mean_bias_V);
nominal.endpoint_voltage_error_V = ...
    0.5 * limits.endpoint_voltage_error_V;
nominal.surface_temperature_error = metric( ...
    acceptance_cfg.minimum_comparable_samples, ...
    0.5 * limits.surface_temperature_rms_error_C, ...
    0.5 * limits.surface_temperature_maximum_error_C, ...
    0.5 * limits.surface_temperature_maximum_error_C, 0);
nominal.soc_error = metric(2, ...
    0.5 * limits.endpoint_soc_error_fraction, ...
    0.5 * limits.endpoint_soc_error_fraction, ...
    0.5 * limits.endpoint_soc_error_fraction, 0);
nominal.endpoint_soc_error = 0.5 * limits.endpoint_soc_error_fraction;
nominal.pulse_count = limits.minimum_pulses;
nominal.loaded_voltage_error = metric( ...
    acceptance_cfg.minimum_comparable_samples, ...
    0.5 * limits.loaded_rms_voltage_error_V, ...
    0.5 * limits.maximum_loaded_voltage_error_V, ...
    0.5 * limits.maximum_loaded_voltage_error_V, 0);
nominal.relaxation_voltage_error = metric( ...
    acceptance_cfg.minimum_comparable_samples, ...
    0.5 * limits.relaxation_rms_voltage_error_V, ...
    0.5 * limits.relaxation_rms_voltage_error_V, ...
    0.5 * limits.relaxation_rms_voltage_error_V, 0);

nominal_result = hil.evaluate_validation_acceptance( ...
    nominal, acceptance_cfg, 'hppc');

bad_accuracy = nominal;
bad_accuracy.voltage_error.rms = 2 * limits.rms_voltage_error_V;
bad_accuracy_result = hil.evaluate_validation_acceptance( ...
    bad_accuracy, acceptance_cfg, 'hppc');

missing_temperature = nominal;
missing_temperature.surface_temperature_error = hil.metrics([]);
missing_temperature_result = hil.evaluate_validation_acceptance( ...
    missing_temperature, acceptance_cfg, 'hppc');

report = struct();
report.nominal_case_passed = nominal_result.passed;
report.excessive_error_rejected = ...
    ~bad_accuracy_result.passed && ...
    ismember('rms_voltage_error', bad_accuracy_result.failed_checks);
report.missing_required_temperature_rejected = ...
    ~acceptance_cfg.require_surface_temperature || ...
    (~missing_temperature_result.passed && ...
     ismember('surface_temperature_available', ...
              missing_temperature_result.failed_checks));
report.temperature_interpolation_finite = ...
    all(structfun(@finite_numeric_scalar, limits));
report.passed = report.nominal_case_passed && ...
    report.excessive_error_rejected && ...
    report.missing_required_temperature_rejected && ...
    report.temperature_interpolation_finite;
end

function value = metric(count, rms_value, maximum, p95, bias)
value = struct( ...
    'count', count, ...
    'rms', rms_value, ...
    'mean_bias', bias, ...
    'bias_corrected_rms', rms_value, ...
    'maximum_absolute', maximum, ...
    'p95_absolute', p95, ...
    'p99_absolute', maximum);
end

function result = finite_numeric_scalar(value)
result = ~isnumeric(value) || ...
    (isscalar(value) && isfinite(value));
end
