function [cfg, report] = validate_configuration(cfg)
%VALIDATE_CONFIGURATION Validate one configuration contract.

if ~isstruct(cfg) || ~isscalar(cfg)
    error('hil:config:InvalidType', 'Configuration must be one scalar struct.');
end

if ~isfield(cfg, 'kind')
    error('hil:config:MissingKind', 'Configuration is missing field "kind".');
end

kind = lower(char(cfg.kind));
report = struct('kind', kind, 'warnings', {{}}, 'valid', false);

switch kind
    case 'cell'
        required = { ...
            'id', 'manufacturer', 'model', 'nominal_capacity_Ah', ...
            'nominal_voltage_V', 'minimum_voltage_V', 'maximum_voltage_V', ...
            'maximum_charge_current_A', 'maximum_discharge_current_A', ...
            'soc_breakpoints', 'ocv_soc_breakpoints', ...
            'temperature_breakpoints_C', 'temperature_model_limits_C', ...
            'current_sign', 'dataset_adapter', 'parameter_fit_options', ...
            'thermal_prior', 'provenance'};
        require_fields(cfg, required);

        is_template = isfield(cfg, 'is_template') && logical(cfg.is_template);
        if is_template
            report.warnings{end + 1} = ...
                'Template configuration contains placeholders and cannot be built.';
        else
            positive_scalar(cfg.nominal_capacity_Ah, 'nominal_capacity_Ah');
            positive_scalar(cfg.nominal_voltage_V, 'nominal_voltage_V');
            positive_scalar(cfg.minimum_voltage_V, 'minimum_voltage_V');
            positive_scalar(cfg.maximum_voltage_V, 'maximum_voltage_V');
            positive_scalar(cfg.maximum_charge_current_A, 'maximum_charge_current_A');
            positive_scalar(cfg.maximum_discharge_current_A, 'maximum_discharge_current_A');
        end

        if ~is_template && cfg.minimum_voltage_V >= cfg.maximum_voltage_V
            error('hil:config:VoltageLimits', ...
                'minimum_voltage_V must be below maximum_voltage_V.');
        end

        cfg.soc_breakpoints = monotonic_axis(cfg.soc_breakpoints, ...
            'soc_breakpoints', 0.0, 1.0);
        cfg.ocv_soc_breakpoints = monotonic_axis(cfg.ocv_soc_breakpoints, ...
            'ocv_soc_breakpoints', 0.0, 1.0);
        cfg.temperature_breakpoints_C = monotonic_axis( ...
            cfg.temperature_breakpoints_C, 'temperature_breakpoints_C', -100, 200);

        limits = double(cfg.temperature_model_limits_C(:));
        if numel(limits) ~= 2 || any(~isfinite(limits)) || limits(1) >= limits(2)
            error('hil:config:TemperatureLimits', ...
                'temperature_model_limits_C must be [minimum maximum].');
        end
        cfg.temperature_model_limits_C = limits(:).';

        if ~strcmpi(char(cfg.current_sign), 'positive_discharge')
            error('hil:config:CurrentSign', ...
                'Internal current convention must be "positive_discharge".');
        end
        if isfield(cfg.parameter_fit_options, 'holdout_cell_ids')
            fit_ids = cellstr(string(cfg.parameter_fit_options.cell_ids));
            holdout_ids = cellstr(string( ...
                cfg.parameter_fit_options.holdout_cell_ids));
            if isempty(fit_ids) || isempty(holdout_ids) || ...
                    ~isempty(intersect(fit_ids, holdout_ids))
                error('hil:config:CellPartition', ...
                    ['parameter_fit_options cell_ids and holdout_cell_ids ' ...
                     'must be nonempty and disjoint.']);
            end
        end

    case 'pack'
        required = { ...
            'id', 'series_groups', 'parallel_cells', 'segment_count', ...
            'groups_per_segment', 'group_to_segment', ...
            'temperature_sensor_count', 'temp_sensor_to_group', ...
            'temp_sensor_location_type', 'temp_sensor_core_weight', ...
            'initial_soc', 'initial_temperature_C', ...
            'minimum_group_voltage_V', 'maximum_group_voltage_V', ...
            'imbalance_model', 'thermal_layout', 'cooling_boundary'};
        require_fields(cfg, required);

        positive_integer(cfg.series_groups, 'series_groups');
        positive_integer(cfg.parallel_cells, 'parallel_cells');
        positive_integer(cfg.segment_count, 'segment_count');
        positive_integer(cfg.temperature_sensor_count, 'temperature_sensor_count');

        cfg.groups_per_segment = double(cfg.groups_per_segment(:).');
        if numel(cfg.groups_per_segment) ~= cfg.segment_count || ...
                any(cfg.groups_per_segment < 1) || ...
                any(mod(cfg.groups_per_segment, 1) ~= 0) || ...
                sum(cfg.groups_per_segment) ~= cfg.series_groups
            error('hil:config:SegmentCounts', ...
                ['groups_per_segment must contain one positive integer per ' ...
                 'segment and sum to series_groups.']);
        end

        cfg.group_to_segment = double(cfg.group_to_segment(:).');
        if numel(cfg.group_to_segment) ~= cfg.series_groups || ...
                any(cfg.group_to_segment < 1) || ...
                any(cfg.group_to_segment > cfg.segment_count) || ...
                any(mod(cfg.group_to_segment, 1) ~= 0)
            error('hil:config:GroupMapping', ...
                'group_to_segment must map every series group to a valid segment.');
        end
        mapped_counts = accumarray(cfg.group_to_segment(:), 1, ...
            [cfg.segment_count, 1]).';
        if ~isequal(mapped_counts, cfg.groups_per_segment)
            error('hil:config:MappingCountMismatch', ...
                'group_to_segment counts do not match groups_per_segment.');
        end

        cfg.temp_sensor_to_group = double(cfg.temp_sensor_to_group(:).');
        if numel(cfg.temp_sensor_to_group) ~= cfg.temperature_sensor_count || ...
                any(cfg.temp_sensor_to_group < 1) || ...
                any(cfg.temp_sensor_to_group > cfg.series_groups) || ...
                any(mod(cfg.temp_sensor_to_group, 1) ~= 0)
            error('hil:config:TemperatureMapping', ...
                'temp_sensor_to_group must map every sensor to a valid group.');
        end

        if numel(cfg.temp_sensor_location_type) ~= cfg.temperature_sensor_count
            error('hil:config:TemperatureLocationCount', ...
                'temp_sensor_location_type length must equal temperature_sensor_count.');
        end

        cfg.temp_sensor_core_weight = double(cfg.temp_sensor_core_weight(:).');
        if numel(cfg.temp_sensor_core_weight) ~= cfg.temperature_sensor_count || ...
                any(~isfinite(cfg.temp_sensor_core_weight)) || ...
                any(cfg.temp_sensor_core_weight < 0) || ...
                any(cfg.temp_sensor_core_weight > 1)
            error('hil:config:TemperatureWeights', ...
                'temp_sensor_core_weight entries must be finite and in [0,1].');
        end

        unit_interval(cfg.initial_soc, 'initial_soc');
        finite_scalar(cfg.initial_temperature_C, 'initial_temperature_C');
        positive_scalar(cfg.minimum_group_voltage_V, 'minimum_group_voltage_V');
        positive_scalar(cfg.maximum_group_voltage_V, 'maximum_group_voltage_V');
        if cfg.minimum_group_voltage_V >= cfg.maximum_group_voltage_V
            error('hil:config:GroupVoltageLimits', ...
                'minimum_group_voltage_V must be below maximum_group_voltage_V.');
        end

        valid_modes = {'uniform', 'deterministic_spread', 'parameter_distributed'};
        require_fields(cfg.imbalance_model, {'mode', 'seed'});
        mode = lower(char(cfg.imbalance_model.mode));
        if ~ismember(mode, valid_modes)
            error('hil:config:ImbalanceMode', ...
                'Unsupported imbalance mode "%s".', cfg.imbalance_model.mode);
        end
        finite_scalar(cfg.imbalance_model.seed, 'imbalance_model.seed');
        if strcmp(mode, 'deterministic_spread') || ...
                strcmp(mode, 'parameter_distributed')
            spread_fields = { ...
                'voltage_peak_to_peak_V', 'soc_peak_to_peak', ...
                'temperature_peak_to_peak_C'};
            require_fields(cfg.imbalance_model, spread_fields);
            for index = 1:numel(spread_fields)
                nonnegative_scalar(cfg.imbalance_model.(spread_fields{index}), ...
                    ['imbalance_model.', spread_fields{index}]);
            end
        end
        if strcmp(mode, 'parameter_distributed')
            sigma_fields = { ...
                'capacity_sigma_fraction', 'r0_sigma_fraction', ...
                'r1_sigma_fraction', 'c1_sigma_fraction', ...
                'r2_sigma_fraction', 'c2_sigma_fraction', ...
                'initial_soc_sigma', 'thermal_resistance_sigma_fraction'};
            bound_fields = { ...
                'capacity_bounds_fraction', 'r0_bounds_fraction', ...
                'r1_bounds_fraction', 'c1_bounds_fraction', ...
                'r2_bounds_fraction', 'c2_bounds_fraction', ...
                'thermal_resistance_bounds_fraction'};
            require_fields(cfg.imbalance_model, ...
                [sigma_fields, bound_fields, {'initial_soc_bounds'}]);
            for index = 1:numel(sigma_fields)
                nonnegative_scalar(cfg.imbalance_model.(sigma_fields{index}), ...
                    ['imbalance_model.', sigma_fields{index}]);
            end
            for index = 1:numel(bound_fields)
                multiplier_bounds(cfg.imbalance_model.(bound_fields{index}), ...
                    ['imbalance_model.', bound_fields{index}]);
            end
            soc_bounds = double(cfg.imbalance_model.initial_soc_bounds(:));
            if numel(soc_bounds) ~= 2 || any(~isfinite(soc_bounds)) || ...
                    soc_bounds(1) > 0 || soc_bounds(2) < 0 || ...
                    soc_bounds(1) >= soc_bounds(2)
                error('hil:config:SoCOffsetBounds', ...
                    'initial_soc_bounds must be increasing and contain zero.');
            end
            if isfield(cfg.imbalance_model, 'overrides') && ...
                    ~isstruct(cfg.imbalance_model.overrides)
                error('hil:config:GroupOverrides', ...
                    'imbalance_model.overrides must be a struct or struct array.');
            end
        end
        require_fields(cfg.cooling_boundary, {'mode', 'Rsa_multiplier'});
        positive_scalar(cfg.cooling_boundary.Rsa_multiplier, ...
            'cooling_boundary.Rsa_multiplier');

    case 'simulation'
        required = { ...
            'id', 'sample_time_s', 'stop_time_s', 'profile', ...
            'ambient_temperature_C', 'initial_soc', ...
            'measurement_noise', 'current_bias_A', 'fault_injection', ...
            'output_directory', 'engine'};
        require_fields(cfg, required);
        positive_scalar(cfg.sample_time_s, 'sample_time_s');
        if ischar(cfg.stop_time_s) || isstring(cfg.stop_time_s)
            if ~strcmpi(char(cfg.stop_time_s), 'profile')
                error('hil:config:StopTime', ...
                    'String stop_time_s must be "profile".');
            end
        else
            positive_scalar(cfg.stop_time_s, 'stop_time_s');
        end
        finite_scalar(cfg.ambient_temperature_C, 'ambient_temperature_C');
        unit_interval(cfg.initial_soc, 'initial_soc');
        require_fields(cfg.profile, { ...
            'name', 'kind', 'scaling_mode', 'repeat_policy'});
        valid_profile_kinds = { ...
            'synthetic_hppc', 'embedded_c_header', 'csv', 'mat', ...
            'constant_current', 'constant_power'};
        if ~ismember(lower(char(cfg.profile.kind)), valid_profile_kinds)
            error('hil:config:ProfileKind', ...
                'Unsupported profile kind "%s".', cfg.profile.kind);
        end
        valid_scaling = { ...
            'no_scaling', 'vehicle_current_replay', 'constant_c_rate', ...
            'constant_cell_current', 'constant_pack_power'};
        if ~ismember(lower(char(cfg.profile.scaling_mode)), valid_scaling)
            error('hil:config:ScalingMode', ...
                'Unsupported profile scaling_mode "%s".', ...
                cfg.profile.scaling_mode);
        end
        valid_repeat = {'one_shot', 'repeat', 'repeat_count'};
        if ~ismember(lower(char(cfg.profile.repeat_policy)), valid_repeat)
            error('hil:config:RepeatPolicy', ...
                'Unsupported profile repeat_policy.');
        end
        if strcmpi(cfg.profile.repeat_policy, 'repeat_count')
            require_fields(cfg.profile, {'repeat_count'});
            positive_integer(cfg.profile.repeat_count, ...
                'profile.repeat_count');
        end
        require_fields(cfg.measurement_noise, { ...
            'voltage_std_V', 'current_std_A', ...
            'temperature_std_C', 'seed'});
        noise_fields = {'voltage_std_V', 'current_std_A', 'temperature_std_C'};
        for index = 1:numel(noise_fields)
            nonnegative_scalar(cfg.measurement_noise.(noise_fields{index}), ...
                ['measurement_noise.', noise_fields{index}]);
        end
        finite_scalar(cfg.measurement_noise.seed, 'measurement_noise.seed');
        finite_scalar(cfg.current_bias_A, 'current_bias_A');
        if isfield(cfg, 'output_decimation')
            positive_integer(cfg.output_decimation, 'output_decimation');
        end

    case 'dataset'
        required = { ...
            'id', 'adapter', 'root', 'current_sign', 'units', ...
            'source', 'version'};
        require_fields(cfg, required);
        valid_signs = {'positive_discharge', 'negative_discharge', 'auto'};
        if ~ismember(lower(char(cfg.current_sign)), valid_signs)
            error('hil:config:DatasetCurrentSign', ...
                'Dataset current_sign must be positive_discharge, negative_discharge, or auto.');
        end
        if isempty(regexp(char(cfg.adapter), '^[A-Za-z][A-Za-z0-9_]*$', 'once'))
            error('hil:config:DatasetAdapter', ...
                'Dataset adapter must be a MATLAB function name.');
        end
        require_fields(cfg.units, { ...
            'time', 'current', 'voltage', 'temperature', 'capacity'});
        if isfield(cfg, 'fit_cell_ids') || isfield(cfg, 'holdout_cell_ids')
            require_fields(cfg, {'fit_cell_ids', 'holdout_cell_ids'});
            fit_ids = cellstr(string(cfg.fit_cell_ids));
            holdout_ids = cellstr(string(cfg.holdout_cell_ids));
            if isempty(fit_ids) || isempty(holdout_ids) || ...
                    ~isempty(intersect(fit_ids, holdout_ids))
                error('hil:config:DatasetPartition', ...
                    'Dataset fit_cell_ids and holdout_cell_ids must be disjoint.');
            end
        end

    case 'acceptance'
        required = { ...
            'id', 'cell_configuration', 'revision', ...
            'qualification_scope', 'status', ...
            'minimum_comparable_samples', ...
            'require_surface_temperature', 'require_soc_reference', ...
            'hppc', 'dynamic', 'rationale'};
        require_fields(cfg, required);
        nonempty_text(cfg.revision, 'revision');
        nonempty_text(cfg.qualification_scope, 'qualification_scope');
        nonempty_text(cfg.status, 'status');
        positive_integer(cfg.minimum_comparable_samples, ...
            'minimum_comparable_samples');
        logical_scalar(cfg.require_surface_temperature, ...
            'require_surface_temperature');
        logical_scalar(cfg.require_soc_reference, ...
            'require_soc_reference');
        validate_acceptance_class(cfg.hppc, 'hppc', true);
        validate_acceptance_class(cfg.dynamic, 'dynamic', false);
        if ~iscell(cfg.rationale) || isempty(cfg.rationale)
            error('hil:config:AcceptanceRationale', ...
                'Acceptance configuration requires a nonempty rationale cell array.');
        end

    otherwise
        error('hil:config:UnknownKind', 'Unknown configuration kind "%s".', kind);
end

report.valid = true;
end

function require_fields(value, names)
for index = 1:numel(names)
    if ~isfield(value, names{index})
        error('hil:config:MissingField', ...
            'Configuration is missing required field "%s".', names{index});
    end
end
end

function positive_scalar(value, name)
if ~(isnumeric(value) && isscalar(value) && isfinite(value) && value > 0)
    error('hil:config:PositiveScalar', '%s must be a positive finite scalar.', name);
end
end

function nonnegative_scalar(value, name)
if ~(isnumeric(value) && isscalar(value) && isfinite(value) && value >= 0)
    error('hil:config:NonnegativeScalar', ...
        '%s must be a nonnegative finite scalar.', name);
end
end

function finite_scalar(value, name)
if ~(isnumeric(value) && isscalar(value) && isfinite(value))
    error('hil:config:FiniteScalar', '%s must be a finite scalar.', name);
end
end

function logical_scalar(value, name)
if ~(islogical(value) && isscalar(value))
    error('hil:config:LogicalScalar', '%s must be one logical scalar.', name);
end
end

function nonempty_text(value, name)
if ~((ischar(value) || (isstring(value) && isscalar(value))) && ...
        strlength(strtrim(string(value))) > 0)
    error('hil:config:NonemptyText', '%s must be nonempty text.', name);
end
end

function positive_integer(value, name)
positive_scalar(value, name);
if mod(double(value), 1) ~= 0
    error('hil:config:PositiveInteger', '%s must be an integer.', name);
end
end

function validate_acceptance_class(value, name, require_pulse_metrics)
common = { ...
    'temperature_breakpoints_C', ...
    'rms_voltage_error_V', ...
    'maximum_voltage_error_V', ...
    'p95_voltage_error_V', ...
    'absolute_mean_bias_V', ...
    'endpoint_voltage_error_V', ...
    'endpoint_soc_error_fraction', ...
    'surface_temperature_rms_error_C', ...
    'surface_temperature_maximum_error_C'};
require_fields(value, common);
if require_pulse_metrics
    require_fields(value, { ...
        'loaded_rms_voltage_error_V', ...
        'maximum_loaded_voltage_error_V', ...
        'relaxation_rms_voltage_error_V', ...
        'minimum_pulses'});
    positive_integer(value.minimum_pulses, [name, '.minimum_pulses']);
end

axis = monotonic_axis(value.temperature_breakpoints_C, ...
    [name, '.temperature_breakpoints_C'], -100, 200);
metric_names = common(2:end);
if require_pulse_metrics
    metric_names = [metric_names, { ...
        'loaded_rms_voltage_error_V', ...
        'maximum_loaded_voltage_error_V', ...
        'relaxation_rms_voltage_error_V'}];
end
for index = 1:numel(metric_names)
    metric = double(value.(metric_names{index})(:));
    if numel(metric) ~= numel(axis) || any(~isfinite(metric)) || ...
            any(metric <= 0)
        error('hil:config:AcceptanceLimit', ...
            '%s.%s must have one positive finite limit per temperature.', ...
            name, metric_names{index});
    end
end
end

function unit_interval(value, name)
finite_scalar(value, name);
if value < 0 || value > 1
    error('hil:config:UnitInterval', '%s must be in [0,1].', name);
end
end

function multiplier_bounds(value, name)
value = double(value(:));
if numel(value) ~= 2 || any(~isfinite(value)) || ...
        value(1) <= 0 || value(1) > 1 || value(2) < 1 || ...
        value(1) >= value(2)
    error('hil:config:MultiplierBounds', ...
        '%s must be increasing, positive, and contain one.', name);
end
end

function axis_out = monotonic_axis(axis_in, name, minimum, maximum)
axis_out = double(axis_in(:));
if numel(axis_out) < 2 || any(~isfinite(axis_out)) || ...
        any(diff(axis_out) <= 0) || axis_out(1) < minimum || ...
        axis_out(end) > maximum
    error('hil:config:Axis', ...
        '%s must be finite, strictly increasing, and inside [%g,%g].', ...
        name, minimum, maximum);
end
end
