function report = validate_thermal_physics(cell_cfg, pack_cfg, sim_cfg, params)
%VALIDATE_THERMAL_PHYSICS Guard zero-heat, lag, relaxation, and monotonicity.

pack_cfg.imbalance_model.mode = 'uniform';
sim_cfg.engine = 'reference';
sim_cfg.initial_soc = 0.80;
sim_cfg.output_decimation = 1;
sample_time = double(sim_cfg.sample_time_s);

zero_profile = profile_for( ...
    (0:sample_time:60).', @(time) zeros(size(time)), 25.0);
zero_pack = pack_cfg;
zero_pack.initial_temperature_C = 25.0;
zero_result = hil.run_reference( ...
    cell_cfg, zero_pack, sim_cfg, params, zero_profile);

pulse_time = (0:sample_time:360).';
pulse_profile = profile_for(pulse_time, ...
    @(time) 100.0 * double(time < 60.0), 25.0);
nominal_pack = pack_cfg;
nominal_pack.initial_temperature_C = 25.0;
nominal_result = hil.run_reference( ...
    cell_cfg, nominal_pack, sim_cfg, params, pulse_profile);

hot_pack = nominal_pack;
hot_pack.initial_temperature_C = 40.0;
hot_profile = profile_for(pulse_time, ...
    @(time) 100.0 * double(time < 60.0), 40.0);
hot_result = hil.run_reference( ...
    cell_cfg, hot_pack, sim_cfg, params, hot_profile);

optimistic_pack = nominal_pack;
optimistic_pack.cooling_boundary.Rsa_multiplier = 0.70;
optimistic_result = hil.run_reference( ...
    cell_cfg, optimistic_pack, sim_cfg, params, pulse_profile);
conservative_pack = nominal_pack;
conservative_pack.cooling_boundary.Rsa_multiplier = 1.50;
conservative_result = hil.run_reference( ...
    cell_cfg, conservative_pack, sim_cfg, params, pulse_profile);

load_end = find(nominal_result.time_s <= 60.0, 1, 'last');
gradient_at_load_end = nominal_result.T_core(load_end) - ...
    nominal_result.T_surf(load_end);
gradient_at_end = nominal_result.T_core(end) - nominal_result.T_surf(end);
checks = struct();
checks.zero_current_isothermal = ...
    max(abs(zero_result.T_core - 25.0)) < 1e-9 && ...
    max(abs(zero_result.T_surf - 25.0)) < 1e-9;
checks.positive_heat_raises_core = ...
    nominal_result.T_core(load_end) > 25.0 && gradient_at_load_end > 0;
checks.core_surface_gradient_relaxes = ...
    abs(gradient_at_end) < abs(gradient_at_load_end);
checks.thermal_state_bounded = ...
    all(isfinite(nominal_result.T_core)) && ...
    all(isfinite(nominal_result.T_surf)) && ...
    max(nominal_result.T_core) < 200.0;
checks.hotter_ambient_not_cooler = ...
    max(hot_result.T_core) >= max(nominal_result.T_core);
checks.higher_Rsa_not_better = ...
    max(conservative_result.T_core) + 1e-7 >= ...
    max(optimistic_result.T_core);

names = fieldnames(checks);
failed = names(~cellfun(@(name) checks.(name), names));
report = struct( ...
    'passed', isempty(failed), ...
    'checks', checks, ...
    'failed_checks', {failed}, ...
    'gradient_at_load_end_C', gradient_at_load_end, ...
    'gradient_after_relaxation_C', gradient_at_end, ...
    'nominal_peak_core_C', max(nominal_result.T_core), ...
    'hot_peak_core_C', max(hot_result.T_core), ...
    'optimistic_peak_core_C', max(optimistic_result.T_core), ...
    'conservative_peak_core_C', max(conservative_result.T_core));
if ~report.passed
    error('hil:validation:ThermalPhysics', ...
        'Thermal physics checks failed: %s', strjoin(failed, ', '));
end
end

function profile = profile_for(time, current_factory, ambient)
profile = struct( ...
    'time_s', time, ...
    'pack_current_A', current_factory(time), ...
    'ambient_temperature_C', repmat(double(ambient), size(time)), ...
    'name', 'thermal_physics_guard', ...
    'source', 'hil.validate_thermal_physics', ...
    'sample_time_s', median(diff(time)), ...
    'repeat_policy', 'one_shot', ...
    'scaling_mode', 'no_scaling');
end
