function report = validate_parameters(cell_cfg, params)
%VALIDATE_PARAMETERS Check axes, dimensions, finiteness, and physical signs.

[cell_cfg, ~] = hil.validate_configuration(cell_cfg);
expected_ecm = [numel(cell_cfg.soc_breakpoints), ...
    numel(cell_cfg.temperature_breakpoints_C)];
expected_ocv = [numel(cell_cfg.ocv_soc_breakpoints), ...
    numel(cell_cfg.temperature_breakpoints_C)];

checks = struct();
checks.ocv_dimensions = isequal(size(params.OCV), expected_ocv);
checks.r0_dimensions = isequal(size(params.R0), expected_ecm);
checks.r1_dimensions = isequal(size(params.R1), expected_ecm);
checks.c1_dimensions = isequal(size(params.C1), expected_ecm);
checks.finite_tables = all(isfinite(double(params.OCV(:)))) && ...
    all(isfinite(double(params.R0(:)))) && ...
    all(isfinite(double(params.R1(:)))) && ...
    all(isfinite(double(params.C1(:))));
checks.positive_resistances = all(double(params.R0(:)) > 0) && ...
    all(double(params.R1(:)) > 0) && double(params.R2) > 0;
checks.positive_capacitances = all(double(params.C1(:)) > 0) && ...
    double(params.C2) > 0 && double(params.Cc) > 0 && double(params.Cs) > 0;
checks.positive_thermal_resistance = ...
    double(params.Rcs) > 0 && double(params.Rsa) > 0;
checks.ocv_inside_limits = min(double(params.OCV(:))) >= ...
    cell_cfg.minimum_voltage_V - 0.1 && ...
    max(double(params.OCV(:))) <= cell_cfg.maximum_voltage_V + 0.1;
checks.tau1_bounded = all(double(params.R1(:) .* params.C1(:)) > 0.05) && ...
    all(double(params.R1(:) .* params.C1(:)) < 5000);
checks.tau2_bounded = double(params.R2 * params.C2) > 0.1 && ...
    double(params.R2 * params.C2) < 10000;

names = fieldnames(checks);
passed = true;
failed = {};
for index = 1:numel(names)
    if ~checks.(names{index})
        passed = false;
        failed{end + 1, 1} = names{index}; %#ok<AGROW>
    end
end

report = struct( ...
    'passed', passed, ...
    'checks', checks, ...
    'failed_checks', {failed}, ...
    'configuration_hash', params.configuration_hash);
if ~passed
    error('hil:params:ValidationFailed', ...
        'Parameter validation failed: %s', strjoin(failed, ', '));
end
end
