function write_esp32_interface_files( ...
    destination, model_name, pack_cfg, model_artifact)
%WRITE_ESP32_INTERFACE_FILES Write the generated-name binding and topology ABI.

header_file = fullfile(destination, [model_name, '.h']);
if ~isfile(header_file)
    error('hil:codegen:ModelHeaderMissing', ...
        'Missing generated model header %s.', header_file);
end
header = fileread(header_file);
model_source_file = fullfile(destination, [model_name, '.c']);
if ~isfile(model_source_file)
    error('hil:codegen:ModelSourceMissing', ...
        'Missing generated model source %s.', model_source_file);
end
dwork_type = token(header, ...
    '}\\s*(DW_[A-Za-z0-9_]+)\\s*;', 'DWork type');
model_type = token(header, ...
    '(RT_MODEL_[A-Za-z0-9_]+)\\s*\\*const', 'model type');

binding = sprintf([ ...
    '#ifndef PLANT_MODEL_BINDING_H_\n' ...
    '#define PLANT_MODEL_BINDING_H_\n\n' ...
    '#include "%s.h"\n\n' ...
    'typedef %s plant_generated_model_t;\n' ...
    'typedef %s plant_generated_dwork_t;\n\n' ...
    '#define PLANT_GENERATED_INITIALIZE %s_initialize\n' ...
    '#define PLANT_GENERATED_STEP %s_step\n' ...
    '#define PLANT_GENERATED_TERMINATE %s_terminate\n\n' ...
    '#define PLANT_DWORK_SOC(dw) ((dw).SoC_Integrator_DSTATE)\n' ...
    '#define PLANT_DWORK_T_CORE(dw) ((dw).T_core_int_DSTATE)\n' ...
    '#define PLANT_DWORK_T_SURF(dw) ((dw).T_surf_int_DSTATE)\n' ...
    '#define PLANT_DWORK_VP1(dw) ((dw).Vp1_Integrator1_DSTATE)\n' ...
    '#define PLANT_DWORK_VP2(dw) ((dw).Vp2_Integrator_DSTATE)\n\n' ...
    '#endif\n'], ...
    model_name, model_type, dwork_type, ...
    model_name, model_name, model_name);
write_text(fullfile(destination, 'plant_model_binding.h'), binding);

groups = uint16(pack_cfg.groups_per_segment(:).');
group_offsets = uint16([0, cumsum(double(groups(1:end - 1)))]);
group_indices = zeros(1, pack_cfg.series_groups, 'uint16');
sensor_indices = zeros(1, pack_cfg.temperature_sensor_count, 'uint16');
segment_sensor_counts = zeros(1, pack_cfg.segment_count, 'uint16');
group_cursor = 0;
sensor_cursor = 0;
sensor_segment = pack_cfg.group_to_segment( ...
    pack_cfg.temp_sensor_to_group(:));
for segment = 1:pack_cfg.segment_count
    selected_groups = find(pack_cfg.group_to_segment == segment) - 1;
    count = numel(selected_groups);
    group_indices(group_cursor + (1:count)) = uint16(selected_groups);
    group_cursor = group_cursor + count;

    selected_sensors = find(sensor_segment == segment) - 1;
    count = numel(selected_sensors);
    sensor_indices(sensor_cursor + (1:count)) = uint16(selected_sensors);
    sensor_cursor = sensor_cursor + count;
    segment_sensor_counts(segment) = uint16(count);
end
sensor_offsets = uint16([0, cumsum(double(segment_sensor_counts(1:end - 1)))]);

manifest = sprintf([ ...
    '#ifndef PLANT_MODEL_MANIFEST_H_\n' ...
    '#define PLANT_MODEL_MANIFEST_H_\n\n' ...
    '#include <stdint.h>\n\n' ...
    '#define PLANT_MODEL_ABI_VERSION 1U\n' ...
    '#define PLANT_MODEL_NAME "%s"\n' ...
    '#define PLANT_MODEL_PARAMETER_HASH "%s"\n' ...
    '#define PLANT_MODEL_CONFIGURATION_HASH "%s"\n' ...
    '#define PLANT_MODEL_SOURCE_SHA256 "%s"\n' ...
    '#define PLANT_MODEL_SAMPLE_TIME_S %.9gf\n' ...
    '#define PLANT_NUM_GROUPS %dU\n' ...
    '#define PLANT_NUM_SEGMENTS %dU\n' ...
    '#define PLANT_NUM_THERMISTORS %dU\n\n' ...
    'static const uint16_t PLANT_SEGMENT_GROUP_OFFSET[PLANT_NUM_SEGMENTS] = %s;\n' ...
    'static const uint16_t PLANT_SEGMENT_GROUP_COUNT[PLANT_NUM_SEGMENTS] = %s;\n' ...
    'static const uint16_t PLANT_SEGMENT_SENSOR_OFFSET[PLANT_NUM_SEGMENTS] = %s;\n' ...
    'static const uint16_t PLANT_SEGMENT_SENSOR_COUNT[PLANT_NUM_SEGMENTS] = %s;\n' ...
    'static const uint16_t PLANT_SEGMENT_GROUP_INDEX[PLANT_NUM_GROUPS] = %s;\n' ...
    'static const uint16_t PLANT_SEGMENT_SENSOR_INDEX[PLANT_NUM_THERMISTORS] = %s;\n\n' ...
    '#endif\n'], ...
    model_name, model_artifact.parameter_hash, ...
    model_artifact.configuration_hash, ...
    hil.file_sha256(model_source_file), ...
    model_artifact_sample_time(model_artifact), ...
    pack_cfg.series_groups, pack_cfg.segment_count, ...
    pack_cfg.temperature_sensor_count, ...
    c_literal(group_offsets), c_literal(groups), ...
    c_literal(sensor_offsets), c_literal(segment_sensor_counts), ...
    c_literal(group_indices), c_literal(sensor_indices));
write_text(fullfile(destination, 'plant_model_manifest.h'), manifest);
end

function value = token(text, pattern, description)
match = regexp(text, pattern, 'tokens', 'once');
if isempty(match)
    error('hil:codegen:HeaderContract', ...
        'Could not identify generated %s.', description);
end
value = match{1};
end

function value = c_literal(values)
tokens = arrayfun(@(x) sprintf('%dU', x), double(values(:).'), ...
    'UniformOutput', false);
value = ['{ ', strjoin(tokens, ', '), ' }'];
end

function value = model_artifact_sample_time(model_artifact)
if isfield(model_artifact, 'simulation_configuration')
    value = model_artifact.simulation_configuration.sample_time_s;
else
    manifest = jsondecode(fileread(model_artifact.manifest_file));
    value = manifest.simulation_configuration.sample_time_s;
end
end

function write_text(file_path, content)
file = fopen(file_path, 'w');
if file < 0
    error('hil:file:WriteFailed', 'Could not write %s.', file_path);
end
cleanup = onCleanup(@() fclose(file)); %#ok<NASGU>
fprintf(file, '%s', content);
end
