function names = core_campaign()
%CORE_CAMPAIGN Frozen compact C0-C8 deterministic qualification inventory.
names={ ...
    'c0_bootstrap_current', ...
    'c1_hppc_bad_init', ...
    'c2_low_soc_sop', ...
    'c3_high_soc_charge_sop', ...
    'c4_hot_weak_group', ...
    'c5_soh_capacity_resistance', ...
    'c6_fuse_transient', ...
    'c7_measurement_faults', ...
    'c8_dynamic_replay'};
end
