function cfg = default_config()
%DEFAULT_CONFIG Base MiL scenario with conservative, explicit assumptions.
%
% Measurement-noise values here are DEVELOPMENT priors, not hardware
% qualification claims. Qualification configurations must replace them with
% measured sensor/ADBMS statistics and freeze the resulting configuration.

cfg = struct();
cfg.schema_version = 1;
cfg.id = 'base';
cfg.description = 'DER26 distributed-plant MiL base configuration';
cfg.requirements = {};
cfg.seed = 260826;

cfg.cell_id = 'p42a';
cfg.pack_id = 'der26_75s6p';
cfg.simulation_id = 'us06_25c';
cfg.initial_soc = 0.80;
cfg.initial_temperature_C = 25.0;
cfg.ambient_temperature_C = 25.0;
cfg.stop_time_s = 'profile';
cfg.output_decimation = 1;

cfg.plant = struct();
cfg.plant.variation_mode = 'parameter_distributed';
cfg.plant.seed = cfg.seed;
cfg.plant.overrides = struct([]);
cfg.plant.cooling_Rsa_multiplier = 1.0;

cfg.sensor = struct();
cfg.sensor.seed = cfg.seed + 1;
cfg.sensor.voltage_noise_std_V = 0.0015;
cfg.sensor.voltage_bias_V = 0.0;
cfg.sensor.voltage_quantization_V = 0.001;
cfg.sensor.temperature_noise_std_C = 0.25;
cfg.sensor.temperature_bias_C = 0.0;
cfg.sensor.temperature_quantization_C = 0.1;
cfg.sensor.timestamp_jitter_std_s = 0.0;
cfg.sensor.default_cell_age_ms = 0;
cfg.sensor.default_temp_age_ms = 0;
cfg.sensor.max_cell_age_ms = 250;
cfg.sensor.max_temp_age_ms = 250;
cfg.sensor.faults = struct([]);

cfg.sensor.current = struct();
cfg.sensor.current.sample_time_s = 0.020;
cfg.sensor.current.adc_vref_V = 3.3;
cfg.sensor.current.sensor_supply_V = 5.0;
cfg.sensor.current.noise_50A_std_A = 0.05;
cfg.sensor.current.noise_800A_std_A = 0.50;
cfg.sensor.current.bias_50A_A = 0.0;
cfg.sensor.current.bias_800A_A = 0.0;
cfg.sensor.current.gain_50A = 1.0;
cfg.sensor.current.gain_800A = 1.0;
cfg.sensor.current.zero_cal_offset_50A_A = 0.0;
cfg.sensor.current.zero_cal_offset_800A_A = 0.0;
cfg.sensor.current.polarity = 1.0;
cfg.sensor.current.force_range = 'auto';
cfg.sensor.current.calibrated = true;
cfg.sensor.current.polarity_validated = true;
cfg.sensor.current.channel_50A_enabled = true;
cfg.sensor.current.channel_800A_enabled = true;
cfg.sensor.current.faults = struct([]);

cfg.production = struct();
% Most MiL scenarios qualify in-operation behavior, so start the production
% estimator from a real 30 s stationary acquisition performed outside scored
% scenario time. Startup/acquisition-specific scenarios explicitly override
% this to zero and exercise acquisition inside the scored profile.
cfg.production.estimator = struct('enabled',true,'precondition_rest_s',30.0);
cfg.production.sop = struct('enabled',true);
cfg.production.soh = struct('enabled',true);

cfg.reference_ekf = struct();
cfg.reference_ekf.enabled = true;
cfg.reference_ekf.initial_soc_offset = 0.0;
cfg.reference_ekf.initial_soc = cfg.initial_soc;
cfg.reference_ekf.initial_vp1_V = 0.0;
cfg.reference_ekf.initial_vp2_V = 0.0;
cfg.reference_ekf.q_diag = [5e-7, 1e-5, 1e-6];
cfg.reference_ekf.p0_diag = [1e-2, 1e-3, 1e-3];
cfg.reference_ekf.measurement_R_V2 = 2.5e-3;
cfg.reference_ekf.innovation_gate_sigma = 8.0;
cfg.reference_ekf.temperature_lut_bounds_C = [5.0, 40.0];
cfg.reference_ekf.acquisition = struct( ...
    'enabled', false, ...
    'hold_measurement_updates', false, ...
    'dynamic_soc_only_updates', true, ...
    'dynamic_soc_sigma_floor', 0.030, ...
    'dynamic_vp_sigma_floor_V', 0.020, ...
    'dynamic_max_soc_step', 0.030, ...
    'current_enter_A', 0.50, ...
    'current_abort_A', 1.00, ...
    'window_s', 20.0, ...
    'fit_sample_period_s', 1.0, ...
    'min_fit_samples', 15, ...
    'tau1_s', 10.0, ...
    'tau2_s', 35.0, ...
    'min_fit_rcond', 1.0e-5, ...
    'max_fit_rmse_mV_cell', 5.0, ...
    'max_abs_vp_state_V', 0.15, ...
    'max_abs_total_polarization_V', 0.20, ...
    'consensus_soc_max_deviation', 0.015, ...
    'min_consensus_segments', 3, ...
    'max_soc_correction_per_anchor', 0.30, ...
    'soc_sigma_init', 0.030, ...
    'vp1_sigma_init_V', 0.020, ...
    'vp2_sigma_init_V', 0.020);

cfg.sop_oracle = struct();
cfg.sop_oracle.enabled = true;
cfg.sop_oracle.checkpoint_times_s = [10, 30, 60];
cfg.sop_oracle.horizons_s = [0.1, 1.0, 10.0, 30.0];
cfg.sop_oracle.discharge_current_caps_A = [118, 80, 70, 70];
cfg.sop_oracle.charge_current_caps_A = [11.5, 10, 10, 10];
cfg.sop_oracle.cell_uv_V = 2.80;
cfg.sop_oracle.cell_ov_V = 4.15;
cfg.sop_oracle.soc_min = 0.05;
cfg.sop_oracle.soc_max = 0.98;
cfg.sop_oracle.discharge_temp_max_C = 55.0;
cfg.sop_oracle.charge_temp_max_C = 42.0;
cfg.sop_oracle.charge_temp_min_C = 3.0;
cfg.sop_oracle.integration_step_s = 0.02;
cfg.sop_oracle.bisection_iterations = 24;

cfg.fuse = struct();
cfg.fuse.enabled = true;
cfg.fuse.startup_policy = 'cold-soak';
cfg.fuse.current_uncertainty_A = 0.5;
cfg.fuse.temperature_measured_at_fuse = false;
cfg.fuse.model_validated = false;

cfg.acceptance = struct();
cfg.acceptance.ekf = struct( ...
    'acquisition_mode', false, ...
    'convergence_required', true, ...
    'r0_accuracy_required', false, ...
    'r0_min_observations', 5, ...
    'r0_unobservable_drift_required', false, ...
    'soc_rmse_max', 0.020, ...
    'soc_p95_abs_max', 0.040, ...
    'soc_worst_abs_max', 0.075, ...
    'convergence_band', 0.030, ...
    'convergence_hold_s', 10.0, ...
    'convergence_time_max_s', 60.0, ...
    'r0_relative_error_p95_max', 0.15, ...
    'r0_unobservable_step_drift_max_ohm', 1.0e-5, ...
    'nis_mean_alpha', 0.01, ...
    'nees_mean_alpha', 0.01, ...
    'max_reject_fraction', 0.05);
cfg.acceptance.acquisition_fault_recovery = struct( ...
    'enabled', false, ...
    'target_segment', 1, ...
    'fault_end_s', 0.0);
cfg.acceptance.sop = struct( ...
    'numeric_tolerance_A', 0.25, ...
    'unsafe_overprediction_max_A', 2.0, ...
    'unsafe_overprediction_max_fraction', 0.02, ...
    'minimum_oracle_self_margin_V', -1e-6);
cfg.acceptance.soh = struct( ...
    'capacity_abs_error_max', 0.05, ...
    'capacity_lower_overconfidence_max', 0.02, ...
    'resistance_upper_underestimate_max', 0.05, ...
    'resistance_abs_error_max', 0.10, ...
    'false_aging_growth_max', 0.10);
cfg.acceptance.fuse = struct( ...
    'state_nonconservative_tolerance', 1.0e-8, ...
    'cap_nonconservative_tolerance_A', 1.0e-6);
cfg.acceptance.global = struct( ...
    'allow_nan', false, ...
    'allow_inf', false, ...
    'deterministic_repeat_tolerance', 0.0);

cfg.gates = struct('ekf',true,'soh',false,'soh_capacity',true, ...
    'soh_resistance',false,'soh_false_aging',false, ...
    'sop',true,'numeric',true,'fault_boundary',true);

cfg.reporting = struct();
cfg.reporting.export_mat = true;
cfg.reporting.export_json = true;
cfg.reporting.export_csv = true;
cfg.reporting.make_plots = false;
end
